package ins.sino.claimcar.common.lossindex.vo;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!
import java.math.BigDecimal;
import java.util.Date;


/**
 * Vo Base Class of PO PrpLDlossIndex
 */ 
public class PrpLDlossIndexVoBase implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Long id;
	private Long bussTaskId;
	private String registNo;
	private String nodeCode;
	private String nodeItem;
	private String handlerCode;
	private String handlerName;
	private String handlerIdNo;
	private String comCode;
	private Date defEndDate;
	private BigDecimal firstVeriLoss;
	private BigDecimal firstDefLoss;
	private String veripHandlerCode;
	private String veripHandlerName;
	private String veripIdNo;
	private String veripCom;
	private Date veripEnddate;
	private BigDecimal sumVeripLoss;
	private String underWriteCode;
	private String underWriteName;
	private String underWiteIdNo;
	private String underWriteCom;
	private Date underWriteEndDate;
	private BigDecimal sumVeriLossFee;
	private BigDecimal preSumFee;
	private Integer quantity;

    protected PrpLDlossIndexVoBase() {
	
    }

    
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getBussTaskId() {
		return this.bussTaskId;
	}

	public void setBussTaskId(Long bussTaskId) {
		this.bussTaskId = bussTaskId;
	}

	public String getRegistNo() {
		return this.registNo;
	}

	public void setRegistNo(String registNo) {
		this.registNo = registNo;
	}

	public String getNodeCode() {
		return this.nodeCode;
	}

	public void setNodeCode(String nodeCode) {
		this.nodeCode = nodeCode;
	}

	public String getNodeItem() {
		return this.nodeItem;
	}

	public void setNodeItem(String nodeItem) {
		this.nodeItem = nodeItem;
	}

	public String getHandlerCode() {
		return this.handlerCode;
	}

	public void setHandlerCode(String handlerCode) {
		this.handlerCode = handlerCode;
	}

	public String getHandlerName() {
		return this.handlerName;
	}

	public void setHandlerName(String handlerName) {
		this.handlerName = handlerName;
	}

	public String getHandlerIdNo() {
		return this.handlerIdNo;
	}

	public void setHandlerIdNo(String handlerIdNo) {
		this.handlerIdNo = handlerIdNo;
	}

	public String getComCode() {
		return this.comCode;
	}

	public void setComCode(String comCode) {
		this.comCode = comCode;
	}

	public Date getDefEndDate() {
		return this.defEndDate;
	}

	public void setDefEndDate(Date defEndDate) {
		this.defEndDate = defEndDate;
	}

	public BigDecimal getFirstVeriLoss() {
		return this.firstVeriLoss;
	}

	public void setFirstVeriLoss(BigDecimal firstVeriLoss) {
		this.firstVeriLoss = firstVeriLoss;
	}

	public BigDecimal getFirstDefLoss() {
		return this.firstDefLoss;
	}

	public void setFirstDefLoss(BigDecimal firstDefLoss) {
		this.firstDefLoss = firstDefLoss;
	}

	public String getVeripHandlerCode() {
		return this.veripHandlerCode;
	}

	public void setVeripHandlerCode(String veripHandlerCode) {
		this.veripHandlerCode = veripHandlerCode;
	}

	public String getVeripHandlerName() {
		return this.veripHandlerName;
	}

	public void setVeripHandlerName(String veripHandlerName) {
		this.veripHandlerName = veripHandlerName;
	}
	
	public String getVeripIdNo() {
		return veripIdNo;
	}
	
	public void setVeripIdNo(String veripIdNo) {
		this.veripIdNo = veripIdNo;
	}

	public String getVeripCom() {
		return this.veripCom;
	}

	public void setVeripCom(String veripCom) {
		this.veripCom = veripCom;
	}

	public Date getVeripEnddate() {
		return this.veripEnddate;
	}

	public void setVeripEnddate(Date veripEnddate) {
		this.veripEnddate = veripEnddate;
	}

	public BigDecimal getSumVeripLoss() {
		return this.sumVeripLoss;
	}

	public void setSumVeripLoss(BigDecimal sumVeripLoss) {
		this.sumVeripLoss = sumVeripLoss;
	}

	public String getUnderWriteCode() {
		return this.underWriteCode;
	}

	public void setUnderWriteCode(String underWriteCode) {
		this.underWriteCode = underWriteCode;
	}

	public String getUnderWriteName() {
		return this.underWriteName;
	}

	public void setUnderWriteName(String underWriteName) {
		this.underWriteName = underWriteName;
	}

	public String getUnderWiteIdNo() {
		return this.underWiteIdNo;
	}

	public void setUnderWiteIdNo(String underWiteIdNo) {
		this.underWiteIdNo = underWiteIdNo;
	}

	public String getUnderWriteCom() {
		return this.underWriteCom;
	}

	public void setUnderWriteCom(String underWriteCom) {
		this.underWriteCom = underWriteCom;
	}

	public Date getUnderWriteEndDate() {
		return this.underWriteEndDate;
	}

	public void setUnderWriteEndDate(Date underWriteEndDate) {
		this.underWriteEndDate = underWriteEndDate;
	}

	public BigDecimal getSumVeriLossFee() {
		return this.sumVeriLossFee;
	}

	public void setSumVeriLossFee(BigDecimal sumVeriLossFee) {
		this.sumVeriLossFee = sumVeriLossFee;
	}
	
	public BigDecimal getPreSumFee() {
		return preSumFee;
	}
	
	public void setPreSumFee(BigDecimal preSumFee) {
		this.preSumFee = preSumFee;
	}

	public Integer getQuantity() {
		return quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}
	
	
}
