package ins.sino.claimcar.platform.vo.transKindCodeVo;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!


/**
 * Vo Base Class of PO SysKindcodeconvert
 */ 
public class SysKindcodeconvertVoBase implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private SysKindcodeconvertIdVo id;
	private String codeName;
	private String ciCode;
	private String ciCodeName;
	private String validStatus;
	private String remark;
	private String flag;

    protected SysKindcodeconvertVoBase() {
	
    }

    
	public SysKindcodeconvertIdVo getId() {
		return this.id;
	}

	public void setId(SysKindcodeconvertIdVo id) {
		this.id = id;
	}

	public String getCodeName() {
		return this.codeName;
	}

	public void setCodeName(String codeName) {
		this.codeName = codeName;
	}

	public String getCiCode() {
		return this.ciCode;
	}

	public void setCiCode(String ciCode) {
		this.ciCode = ciCode;
	}

	public String getCiCodeName() {
		return this.ciCodeName;
	}

	public void setCiCodeName(String ciCodeName) {
		this.ciCodeName = ciCodeName;
	}

	public String getValidStatus() {
		return this.validStatus;
	}

	public void setValidStatus(String validStatus) {
		this.validStatus = validStatus;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}
}
