package ins.sino.claimcar.reinsurance.vo;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!
import ins.platform.utils.xstreamconverters.SinosoftDateConverter;
import ins.platform.utils.xstreamconverters.SinosoftDoubleConverter;

import java.util.Date;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;


/**
 * ����������Ϣ
 * @author luows
 */ 
@XStreamAlias("PrpLCompensate")
public class PrpLCompensateVo implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	@XStreamAlias("compensateNo")
	private	String 	compensateNo;	//	���������
	@XStreamAlias("caseNo")
	private	String 	caseNo;	//	�ⰸ��
	@XStreamAlias("classCode")
	private	String	classCode;	//	�������
	@XStreamAlias("riskCode")
	private	String	riskCode;	//	���ִ���
	@XStreamAlias("claimNo")
	private	String 	claimNo;	//	�ⰸ����
	@XStreamAlias("policyNo")
	private	String 	policyNo;	//	��������
	@XStreamAlias("currency")
	private	String 	currency;	//	���Աұ����
	@XStreamConverter(value = SinosoftDoubleConverter.class,strings = {"0.00"})
	private	double	sumLoss;	//	���Ա����ʧ���
	@XStreamAlias("makeCom")
	private	String	makeCom;	//	������
	@XStreamAlias("comCode")
	private	String	comCode;	//	ҵ����������ҵ��Ա���빹����
	@XStreamAlias("handler1Code")
	private	String	handler1Code;	//	����ҵ��Ա����
	@XStreamConverter(value = SinosoftDateConverter.class, strings = {"yyyyMMdd"})
	private	Date	inputDate;	//	�������������
	@XStreamConverter(value = SinosoftDateConverter.class, strings = {"yyyyMMdd"})
	private	Date	underWriteEndDate;	//	�����������
	@XStreamAlias("underWriteFlag")
	private	String	underWriteFlag;	//	�����־
	@XStreamConverter(value = SinosoftDateConverter.class, strings = {"yyyyMMdd"})
	private	Date	endcaseDate;	//	�᰸ʱ��


    public PrpLCompensateVo() {
	
    }

    
	public String getCompensateNo() {
		return this.compensateNo;
	}

	public void setCompensateNo(String compensateNo) {
		this.compensateNo = compensateNo;
	}

	public String getClaimNo() {
		return this.claimNo;
	}

	public void setClaimNo(String claimNo) {
		this.claimNo = claimNo;
	}

	public String getCaseNo() {
		return this.caseNo;
	}

	public void setCaseNo(String caseNo) {
		this.caseNo = caseNo;
	}


	public String getClassCode() {
		return this.classCode;
	}

	public void setclassCode(String classCode) {
		this.classCode = classCode;
	}
	
	
	public double getSumLoss() {
		return this.sumLoss;
	}

	public void setSumLoss(double sumLoss) {
		this.sumLoss = sumLoss;
	}
	
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	public String getPolicyNo() {
		return this.policyNo;
	}

	public void setPolicyNo(String policyNo) {
		this.policyNo = policyNo;
	}
	
	public String getRiskCode() {
		return this.riskCode;
	}

	public void setRiskCode(String riskCode) {
		this.riskCode = riskCode;
	}

	public String getMakeCom() {
		return this.makeCom;
	}

	public void setMakeCom(String makeCom) {
		this.makeCom = makeCom;
	}

	public String getComCode() {
		return this.comCode;
	}

	public void setComCode(String comCode) {
		this.comCode = comCode;
	}

	public String getHandler1Code() {
		return this.handler1Code;
	}

	public void setHandler1Code(String handler1Code) {
		this.handler1Code = handler1Code;
	}

	public Date getInputDate() {
		return this.inputDate;
	}

	public void setInputDate(Date inputDate) {
		this.inputDate = inputDate;
	}

	public Date getUnderWriteEndDate() {
		return this.underWriteEndDate;
	}

	public void setUnderWriteEndDate(Date underWriteEndDate) {
		this.underWriteEndDate = underWriteEndDate;
	}

	public String getUnderWriteFlag() {
		return this.underWriteFlag;
	}

	public void setUnderWriteFlag(String underWriteFlag) {
		this.underWriteFlag = underWriteFlag;
	}

	public Date getEndcaseDate() {
		return this.endcaseDate;
	}

	public void setEndcaseDate(Date endcaseDate) {
		this.endcaseDate = endcaseDate;
	}
}
