package ins.sino.claimcar.reinsurance.vo;

import ins.platform.utils.xstreamconverters.SinosoftDoubleConverter;
import ins.platform.utils.xstreamconverters.SinosoftIntegerConverter;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamConverter;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!

/**
 * ���������Ϣ����ϢPrpLChargeVo
 * @author luows
 * @since (2016��7��26�� ����9:11:16): <br>
 */ 
@XStreamAlias("PrpLCharge")
public class PrpLChargeList implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	@XStreamAlias("compensateNo")
	private String compensateNo; 	
	@XStreamAlias("riskCode")
	private String riskCode;		
	@XStreamAlias("policyNo")
	private String policyNo;		
	@XStreamAlias("serialNo")
	private String serialNo;
	@XStreamAlias("kindCode")		
	private String kindCode;
	@XStreamAlias("kindName")
	private String kindName;		
	@XStreamAlias("chargeCode")
	private String chargeCode;
	@XStreamAlias("chargeName")
	private String chargeName;
	@XStreamAlias("currency")
	private String currency;
	@XStreamConverter(value = SinosoftDoubleConverter.class,strings = {"0.00"})
	private double chargeAmount;
	@XStreamConverter(value = SinosoftDoubleConverter.class,strings = {"0.00"})
	private double sumRealPay;
	@XStreamConverter(value = SinosoftIntegerConverter.class)
	private int dangerNo;
	@XStreamConverter(value = SinosoftDoubleConverter.class,strings = {"0.00"})
	private double exceptDeductiblePay;

    public PrpLChargeList() {
	
    }

	public String getCompensateNo() {
		return this.compensateNo;
	}

	public void setCompensateNo(String compensateNo) {
		this.compensateNo = compensateNo;
	}

	public String getPolicyNo() {
		return this.policyNo;
	}

	public void setPolicyNo(String policyNo) {
		this.policyNo = policyNo;
	}

	public String getRiskCode() {
		return this.riskCode;
	}

	public void setRiskCode(String riskCode) {
		this.riskCode = riskCode;
	}

	public String getKindCode() {
		return this.kindCode;
	}

	public void setKindCode(String kindCode) {
		this.kindCode = kindCode;
	}

	public String getSerialNo() {
		return this.serialNo;
	}

	public void setSerialNo(String serialNo) {
		this.serialNo = serialNo;
	}

	public String getChargeCode() {
		return this.chargeCode;
	}

	public void setChargeCode(String chargeCode) {
		this.chargeCode = chargeCode;
	}

	public String getChargeName() {
		return this.chargeName;
	}

	public void setChargeName(String chargeName) {
		this.chargeName = chargeName;
	}

	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	public String getKindName() {
		return this.kindName;
	}

	public void setKindName(String kindName) {
		this.kindName = kindName;
	}
	
	public double getChargeAmount() {
		return this.chargeAmount;
	}

	public void setChargeAmount(double chargeAmount) {
		this.chargeAmount = chargeAmount;
	}

	public double getSumRealPay() {
		return this.sumRealPay;
	}

	public void setSumRealPay(double sumRealPay) {
		this.sumRealPay = sumRealPay;
	}

	public int getDangerNo() {
		return this.dangerNo;
	}

	public void setDangerNo(int dangerNo) {
		this.dangerNo = dangerNo;
	}

	public double getExceptDeductiblePay() {
		return this.exceptDeductiblePay;
	}

	public void setExceptDeductiblePay(double exceptDeductiblePay) {
		this.exceptDeductiblePay = exceptDeductiblePay;
	}
}
