package ins.sino.claimcar.base.claimyj.po;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.constraints.NotBlank;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * POJO Class PrplyjPartoffers
 */
@Entity
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@TableGenerator(name = "utiSequence", table = "UTISEQUENCE", pkColumnName = "GenName", valueColumnName = "GenValue", pkColumnValue = "PRPLYJPARTOFFERS_PK", allocationSize = 10)
@Table(name = "PRPLYJPARTOFFERS")
public class PrplyjPartoffers implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Long id;
	private PrpLyjlosscarComp prpLyjlosscarComp;
	private String partenquiryId;
	private String nosTock;
	private String quality;
	private String partenquirypriceId;
	private String brand;
	private String priceWithtax;
	private String priceWithouttax;
	private String leadDay;
	private String qualityassurancePeriod;
	private String remark;
	private String quality2;
	private String pricewithtax2;
	private String priceWithouttax2;
	private String leadDay2;
	private String qualityassurancePeriod2;
	private String remark2;
	private String partenquiryPriceid2;
	private Date createTime;
	private Date updateTime;
	private String supplyFlag;

	@Id
	@GeneratedValue(strategy=GenerationType.TABLE,generator="utiSequence" )
	@Column(name = "ID", unique = true, nullable = false, precision=12, scale=0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CARCOMPID", nullable = false)
	public PrpLyjlosscarComp getPrpLyjlosscarComp() {
		return prpLyjlosscarComp;
	}

	public void setPrpLyjlosscarComp(PrpLyjlosscarComp prpLyjlosscarComp) {
		this.prpLyjlosscarComp = prpLyjlosscarComp;
	}

	@Column(name = "PARTENQUIRYID", length=50)
	public String getPartenquiryId() {
		return this.partenquiryId;
	}

	public void setPartenquiryId(String partenquiryId) {
		this.partenquiryId = partenquiryId;
	}

	@Column(name = "NOSTOCK", length=10)
	public String getNosTock() {
		return this.nosTock;
	}

	public void setNosTock(String nosTock) {
		this.nosTock = nosTock;
	}

	@Column(name = "QUALITY", length=30)
	public String getQuality() {
		return this.quality;
	}

	public void setQuality(String quality) {
		this.quality = quality;
	}

	@Column(name = "PARTENQUIRYPRICEID", length=30)
	public String getPartenquirypriceId() {
		return this.partenquirypriceId;
	}

	public void setPartenquirypriceId(String partenquirypriceId) {
		this.partenquirypriceId = partenquirypriceId;
	}

	@Column(name = "BRAND", length=30)
	public String getBrand() {
		return this.brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	@Column(name = "PRICEWITHTAX", length=30)
	public String getPriceWithtax() {
		return this.priceWithtax;
	}

	public void setPriceWithtax(String priceWithtax) {
		this.priceWithtax = priceWithtax;
	}

	@Column(name = "PRICEWITHOUTTAX", length=30)
	public String getPriceWithouttax() {
		return this.priceWithouttax;
	}

	public void setPriceWithouttax(String priceWithouttax) {
		this.priceWithouttax = priceWithouttax;
	}

	@Column(name = "LEADDAY", length=30)
	public String getLeadDay() {
		return this.leadDay;
	}

	public void setLeadDay(String leadDay) {
		this.leadDay = leadDay;
	}

	@Column(name = "QUALITYASSURANCEPERIOD", length=30)
	public String getQualityassurancePeriod() {
		return this.qualityassurancePeriod;
	}

	public void setQualityassurancePeriod(String qualityassurancePeriod) {
		this.qualityassurancePeriod = qualityassurancePeriod;
	}

	@Column(name = "REMARK", length=500)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "QUALITY2", length=30)
	public String getQuality2() {
		return this.quality2;
	}

	public void setQuality2(String quality2) {
		this.quality2 = quality2;
	}

	@Column(name = "PRICEWITHTAX2", length=30)
	public String getPricewithtax2() {
		return this.pricewithtax2;
	}

	public void setPricewithtax2(String pricewithtax2) {
		this.pricewithtax2 = pricewithtax2;
	}

	@Column(name = "PRICEWITHOUTTAX2", length=30)
	public String getPriceWithouttax2() {
		return this.priceWithouttax2;
	}

	public void setPriceWithouttax2(String priceWithouttax2) {
		this.priceWithouttax2 = priceWithouttax2;
	}

	@Column(name = "LEADDAY2", length=30)
	public String getLeadDay2() {
		return this.leadDay2;
	}

	public void setLeadDay2(String leadDay2) {
		this.leadDay2 = leadDay2;
	}

	@Column(name = "QUALITYASSURANCEPERIOD2", length=30)
	public String getQualityassurancePeriod2() {
		return this.qualityassurancePeriod2;
	}

	public void setQualityassurancePeriod2(String qualityassurancePeriod2) {
		this.qualityassurancePeriod2 = qualityassurancePeriod2;
	}

	@Column(name = "REMARK2", length=500)
	public String getRemark2() {
		return this.remark2;
	}

	public void setRemark2(String remark2) {
		this.remark2 = remark2;
	}

	@Column(name = "PARTENQUIRYPRICEID2", length=30)
	public String getPartenquiryPriceid2() {
		return this.partenquiryPriceid2;
	}

	public void setPartenquiryPriceid2(String partenquiryPriceid2) {
		this.partenquiryPriceid2 = partenquiryPriceid2;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATETIME", length=7)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATETIME", length=7)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
	@Column(name = "SUPPLYFLAG", length=20)
	public String getSupplyFlag() {
		return supplyFlag;
	}
	
	public void setSupplyFlag(String supplyFlag) {
		this.supplyFlag = supplyFlag;
	}
}
