package ins.sino.claimcar.losscar.po;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!
import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * POJO Class PrpLDlossCarSubRiskHis
 */
@Entity
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@TableGenerator(name = "utiSequence", table = "UTISEQUENCE", pkColumnName = "GenName", valueColumnName = "GenValue", pkColumnValue = "PRPLDLOSSCARSUBRISKHIS_PK", allocationSize = 10)
@Table(name = "PRPLDLOSSCARSUBRISKHIS")
public class PrpLDlossCarSubRiskHis implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Long id;
	private PrpLDlossCarMainHis prpLDlossCarMainHis;
	private Long subRiskId;
	private String registNo;
	private String riskCode;
	private String kindCode;
	private String kindName;
	private BigDecimal count;
	private BigDecimal subRiskFee;
	private BigDecimal veriCount;
	private BigDecimal veriSubRiskFee;
	private String itemName;
	private String remark;
	private Date inputTime;
	private BigDecimal unitamount;

	@Id
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "utiSequence")
	@Column(name = "ID", unique = true, nullable = false, precision=12, scale=0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="LOSSMAINHISID", nullable = false)
	public PrpLDlossCarMainHis getPrpLDlossCarMainHis() {
		return this.prpLDlossCarMainHis;
	}

	public void setPrpLDlossCarMainHis(PrpLDlossCarMainHis prpLDlossCarMainHis) {
		this.prpLDlossCarMainHis = prpLDlossCarMainHis;
	}

	@Column(name = "SUBRISKID", nullable = false, precision=12, scale=0)
	public Long getSubRiskId() {
		return this.subRiskId;
	}

	public void setSubRiskId(Long subRiskId) {
		this.subRiskId = subRiskId;
	}

	@Column(name = "REGISTNO", nullable = false, length=25)
	public String getRegistNo() {
		return this.registNo;
	}

	public void setRegistNo(String registNo) {
		this.registNo = registNo;
	}

	@Column(name = "RISKCODE", length=10)
	public String getRiskCode() {
		return this.riskCode;
	}

	public void setRiskCode(String riskCode) {
		this.riskCode = riskCode;
	}

	@Column(name = "KINDCODE", length=20)
	public String getKindCode() {
		return this.kindCode;
	}

	public void setKindCode(String kindCode) {
		this.kindCode = kindCode;
	}

	@Column(name = "KINDNAME", length=150)
	public String getKindName() {
		return this.kindName;
	}

	public void setKindName(String kindName) {
		this.kindName = kindName;
	}

	@Column(name = "COUNT", precision=10)
	public BigDecimal getCount() {
		return this.count;
	}

	public void setCount(BigDecimal count) {
		this.count = count;
	}

	@Column(name = "SUBRISKFEE", precision=10)
	public BigDecimal getSubRiskFee() {
		return this.subRiskFee;
	}

	public void setSubRiskFee(BigDecimal subRiskFee) {
		this.subRiskFee = subRiskFee;
	}

	@Column(name = "VERICOUNT", precision=10)
	public BigDecimal getVeriCount() {
		return this.veriCount;
	}

	public void setVeriCount(BigDecimal veriCount) {
		this.veriCount = veriCount;
	}

	@Column(name = "VERISUBRISKFEE", precision=10)
	public BigDecimal getVeriSubRiskFee() {
		return this.veriSubRiskFee;
	}

	public void setVeriSubRiskFee(BigDecimal veriSubRiskFee) {
		this.veriSubRiskFee = veriSubRiskFee;
	}
	
	@Column(name = "ITEMNAME")
	public String getItemName() {
		return itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	@Column(name = "REMARK", length=600)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INPUTTIME", length=7)
	public Date getInputTime() {
		return this.inputTime;
	}

	public void setInputTime(Date inputTime) {
		this.inputTime = inputTime;
	}

	@Column(name = "UNITAMOUNT", precision=14)
	public BigDecimal getUnitamount() {
		return this.unitamount;
	}

	public void setUnitamount(BigDecimal unitamount) {
		this.unitamount = unitamount;
	}
}
