package ins.sino.claimcar.losscar.po;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * POJO Class PrpLDlossCarMainHis
 */
@Entity
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@TableGenerator(name = "utiSequence", table = "UTISEQUENCE", pkColumnName = "GenName", valueColumnName = "GenValue", pkColumnValue = "PRPLDLOSSCARMAINHIS_PK", allocationSize = 10)
@Table(name = "PRPLDLOSSCARMAINHIS")
public class PrpLDlossCarMainHis implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Long id;
	private Long lossCarMainId;
	private Long checkCarId;
	private Long scheduleDeflossId;
	private Long carId;
	private String registNo;
	private String riskCode;
	private String licenseNo;
	private String lflag;
	private String mercyFlag;
	private String deflossCarType;
	private String cetainLossType;
	private String repairFactoryCode;
	private String repairFactoryName;
	private String repairFactoryType;
	private String factoryMobile;
	private String lossLevel;
	private String handlerCode;
	private String handlerName;
	private String handlerIdNo;
	private Date deflossDate;
	private String defSite;
	private String intermFlag;
	private String intermCode;
	private Date sendDate;
	private Date estimatedDate;
	private String lossPart;
	private BigDecimal sumCompFee;
	private BigDecimal sumRepairFee;
	private BigDecimal sumMatFee;
	private BigDecimal sumOutFee;
	private BigDecimal sumRemnant;
	private BigDecimal sumLossFee;
	private BigDecimal actualValue;
	private BigDecimal otherFee;
	private BigDecimal sumRescueFee;
	private BigDecimal sumChargeFee;
	private BigDecimal sumVeripCompFee;
	private BigDecimal sumVeripMatFee;
	private BigDecimal sumVeripRemnant;
	private BigDecimal sumVeripLoss;
	private String veripHandlerCode;
	private String veripHandlerName;
	private String veripCom;
	private Date veripEnddate;
	private String veriPriceFlag;
	private String underWriteCode;
	private String underWriteName;
	private String underWiteIdNo;
	private String underWriteCom;
	private Date underWriteEndDate;
	private String underWriteFlag;
	private BigDecimal sumVeriCompFee;
	private BigDecimal sumVeriRepairFee;
	private BigDecimal sumVeriOutFee;
	private BigDecimal sumVeriMatFee;
	private BigDecimal sumVeriRemnant;
	private BigDecimal sumVeriLossFee;
	private BigDecimal sumVeriRescueFee;
	private BigDecimal veriActualValue;
	private BigDecimal veriOtherFee;
	private BigDecimal sumVeriChargeFee;
	private BigDecimal sumSubRiskFee;
	private BigDecimal sumVeriSubRiskFee;
	private String reCheckFlag;
	private String reCheckCode;
	private String reCheckName;
	private String reCheckIdNo;
	private Integer serialNo;
	private String submitSource;
	private String deflossSourceFlag;
	private Long reLossCarId;
	private String makeCom;
	private String comCode;
	private String validFlag;
	private String remark;
	private String lossState;
	private String recycleFlag;
	private String lossFeeType;
	private Date defEndDate;
	private String auditstatus;
	private String nodeCode;
	private String flowFlag;
	private Integer verifyLevel;
	private Integer maxLevel;
	private String veripidno;
	private String flag;
	private String createUser;
	private Date createTime;
	private String offLineHanding;	//是否线下处理，0-否，1-是
	private String photoStatus;		//快赔照片审核是否通过：11-对方定损照片,12-已方定损照片
	private String repairType;		//推修方式
	private BigDecimal sumVeriManage;//核损管理费
	private BigDecimal sumVeriPManage;//核价管理费
	private BigDecimal sumVeripSelfpay;//核价自付金额
	private BigDecimal sumVeriSelfpay;//核损自付金额
	private BigDecimal sumVeripDerogation;//核价减损合计
	private BigDecimal sumVeriDerogation;//核损减损合计
	private BigDecimal sumManageFee;//定损管理费合计
	private BigDecimal sumSelfPayFee;//定损自付合计
	private BigDecimal sumOuterFee;//定损外修合计
	private BigDecimal sumDerogationFee;//定损减损合计
	private List<PrpLDlossCarSubRiskHis> prpLDlossCarSubRiskHises = new ArrayList<PrpLDlossCarSubRiskHis>(0);
	private List<PrpLDlossCarRepairHis> prpLDlossCarRepairHises = new ArrayList<PrpLDlossCarRepairHis>(0);
	private List<PrpLDlossCarMaterialHis> prpLDlossCarMaterialHises = new ArrayList<PrpLDlossCarMaterialHis>(0);
	private List<PrpLDlossCarCompHis> prpLDlossCarCompHises = new ArrayList<PrpLDlossCarCompHis>(0);
	private List<PrpLLossRepairSumInfoHis> PrpLLossRepairSumInfoHises = new ArrayList<PrpLLossRepairSumInfoHis>(0);
	private PrplLossRuleHis prplLossRuleHis;

	@Id
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "utiSequence")
	@Column(name = "ID", unique = true, nullable = false, precision=12, scale=0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "LOSSCARMAINID", nullable = false, precision=12, scale=0)
	public Long getLossCarMainId() {
		return this.lossCarMainId;
	}

	public void setLossCarMainId(Long lossCarMainId) {
		this.lossCarMainId = lossCarMainId;
	}

	@Column(name = "CHECKCARID", precision=12, scale=0)
	public Long getCheckCarId() {
		return this.checkCarId;
	}

	public void setCheckCarId(Long checkCarId) {
		this.checkCarId = checkCarId;
	}

	@Column(name = "SCHEDULEDEFLOSSID", precision=12, scale=0)
	public Long getScheduleDeflossId() {
		return this.scheduleDeflossId;
	}

	public void setScheduleDeflossId(Long scheduleDeflossId) {
		this.scheduleDeflossId = scheduleDeflossId;
	}

	@Column(name = "CARID", precision=12, scale=0)
	public Long getCarId() {
		return this.carId;
	}

	public void setCarId(Long carId) {
		this.carId = carId;
	}

	@Column(name = "REGISTNO", nullable = false, length=25)
	public String getRegistNo() {
		return this.registNo;
	}

	public void setRegistNo(String registNo) {
		this.registNo = registNo;
	}

	@Column(name = "RISKCODE", length=9)
	public String getRiskCode() {
		return this.riskCode;
	}

	public void setRiskCode(String riskCode) {
		this.riskCode = riskCode;
	}

	@Column(name = "LICENSENO", length=20)
	public String getLicenseNo() {
		return this.licenseNo;
	}

	public void setLicenseNo(String licenseNo) {
		this.licenseNo = licenseNo;
	}

	@Column(name = "LFLAG", length=2)
	public String getLflag() {
		return this.lflag;
	}

	public void setLflag(String lflag) {
		this.lflag = lflag;
	}

	@Column(name = "MERCYFLAG", length=1)
	public String getMercyFlag() {
		return this.mercyFlag;
	}

	public void setMercyFlag(String mercyFlag) {
		this.mercyFlag = mercyFlag;
	}

	@Column(name = "DEFLOSSCARTYPE", length=3)
	public String getDeflossCarType() {
		return this.deflossCarType;
	}

	public void setDeflossCarType(String deflossCarType) {
		this.deflossCarType = deflossCarType;
	}

	@Column(name = "CETAINLOSSTYPE", length=10)
	public String getCetainLossType() {
		return this.cetainLossType;
	}

	public void setCetainLossType(String cetainLossType) {
		this.cetainLossType = cetainLossType;
	}

	@Column(name = "REPAIRFACTORYCODE", length=30)
	public String getRepairFactoryCode() {
		return this.repairFactoryCode;
	}

	public void setRepairFactoryCode(String repairFactoryCode) {
		this.repairFactoryCode = repairFactoryCode;
	}

	@Column(name = "REPAIRFACTORYNAME", length=120)
	public String getRepairFactoryName() {
		return this.repairFactoryName;
	}

	public void setRepairFactoryName(String repairFactoryName) {
		this.repairFactoryName = repairFactoryName;
	}

	@Column(name = "REPAIRFACTORYTYPE", length=10)
	public String getRepairFactoryType() {
		return this.repairFactoryType;
	}

	public void setRepairFactoryType(String repairFactoryType) {
		this.repairFactoryType = repairFactoryType;
	}

	@Column(name = "FACTORYMOBILE", length=20)
	public String getFactoryMobile() {
		return this.factoryMobile;
	}

	public void setFactoryMobile(String factoryMobile) {
		this.factoryMobile = factoryMobile;
	}

	@Column(name = "LOSSLEVEL", length=10)
	public String getLossLevel() {
		return this.lossLevel;
	}

	public void setLossLevel(String lossLevel) {
		this.lossLevel = lossLevel;
	}

	@Column(name = "HANDLERCODE", length=10)
	public String getHandlerCode() {
		return this.handlerCode;
	}

	public void setHandlerCode(String handlerCode) {
		this.handlerCode = handlerCode;
	}

	@Column(name = "HANDLERNAME", length=30)
	public String getHandlerName() {
		return this.handlerName;
	}

	public void setHandlerName(String handlerName) {
		this.handlerName = handlerName;
	}

	@Column(name = "HANDLERIDNO", length=20)
	public String getHandlerIdNo() {
		return this.handlerIdNo;
	}

	public void setHandlerIdNo(String handlerIdNo) {
		this.handlerIdNo = handlerIdNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DEFLOSSDATE", length=7)
	public Date getDeflossDate() {
		return this.deflossDate;
	}

	public void setDeflossDate(Date deflossDate) {
		this.deflossDate = deflossDate;
	}

	@Column(name = "DEFSITE")
	public String getDefSite() {
		return this.defSite;
	}

	public void setDefSite(String defSite) {
		this.defSite = defSite;
	}

	@Column(name = "INTERMFLAG", length=2)
	public String getIntermFlag() {
		return this.intermFlag;
	}

	public void setIntermFlag(String intermFlag) {
		this.intermFlag = intermFlag;
	}

	@Column(name = "INTERMCODE")
	public String getIntermCode() {
		return this.intermCode;
	}

	public void setIntermCode(String intermCode) {
		this.intermCode = intermCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SENDDATE", length=7)
	public Date getSendDate() {
		return this.sendDate;
	}

	public void setSendDate(Date sendDate) {
		this.sendDate = sendDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ESTIMATEDDATE", length=7)
	public Date getEstimatedDate() {
		return this.estimatedDate;
	}

	public void setEstimatedDate(Date estimatedDate) {
		this.estimatedDate = estimatedDate;
	}

	@Column(name = "LOSSPART", length=120)
	public String getLossPart() {
		return this.lossPart;
	}

	public void setLossPart(String lossPart) {
		this.lossPart = lossPart;
	}

	@Column(name = "SUMCOMPFEE", precision=14)
	public BigDecimal getSumCompFee() {
		return this.sumCompFee;
	}

	public void setSumCompFee(BigDecimal sumCompFee) {
		this.sumCompFee = sumCompFee;
	}

	@Column(name = "SUMREPAIRFEE", precision=14)
	public BigDecimal getSumRepairFee() {
		return this.sumRepairFee;
	}

	public void setSumRepairFee(BigDecimal sumRepairFee) {
		this.sumRepairFee = sumRepairFee;
	}

	@Column(name = "SUMMATFEE", precision=14)
	public BigDecimal getSumMatFee() {
		return this.sumMatFee;
	}

	public void setSumMatFee(BigDecimal sumMatFee) {
		this.sumMatFee = sumMatFee;
	}

	@Column(name = "SUMOUTFEE", precision=14)
	public BigDecimal getSumOutFee() {
		return this.sumOutFee;
	}

	public void setSumOutFee(BigDecimal sumOutFee) {
		this.sumOutFee = sumOutFee;
	}

	@Column(name = "SUMREMNANT", precision=14)
	public BigDecimal getSumRemnant() {
		return this.sumRemnant;
	}

	public void setSumRemnant(BigDecimal sumRemnant) {
		this.sumRemnant = sumRemnant;
	}

	@Column(name = "SUMLOSSFEE", precision=14)
	public BigDecimal getSumLossFee() {
		return this.sumLossFee;
	}

	public void setSumLossFee(BigDecimal sumLossFee) {
		this.sumLossFee = sumLossFee;
	}

	@Column(name = "ACTUALVALUE", precision=14)
	public BigDecimal getActualValue() {
		return this.actualValue;
	}

	public void setActualValue(BigDecimal actualValue) {
		this.actualValue = actualValue;
	}

	@Column(name = "OTHERFEE", precision=14)
	public BigDecimal getOtherFee() {
		return this.otherFee;
	}

	public void setOtherFee(BigDecimal otherFee) {
		this.otherFee = otherFee;
	}

	@Column(name = "SUMRESCUEFEE", precision=14)
	public BigDecimal getSumRescueFee() {
		return this.sumRescueFee;
	}

	public void setSumRescueFee(BigDecimal sumRescueFee) {
		this.sumRescueFee = sumRescueFee;
	}

	@Column(name = "SUMCHARGEFEE", precision=14)
	public BigDecimal getSumChargeFee() {
		return this.sumChargeFee;
	}

	public void setSumChargeFee(BigDecimal sumChargeFee) {
		this.sumChargeFee = sumChargeFee;
	}

	@Column(name = "SUMVERIPCOMPFEE", precision=14)
	public BigDecimal getSumVeripCompFee() {
		return this.sumVeripCompFee;
	}

	public void setSumVeripCompFee(BigDecimal sumVeripCompFee) {
		this.sumVeripCompFee = sumVeripCompFee;
	}

	@Column(name = "SUMVERIPMATFEE", precision=14)
	public BigDecimal getSumVeripMatFee() {
		return this.sumVeripMatFee;
	}

	public void setSumVeripMatFee(BigDecimal sumVeripMatFee) {
		this.sumVeripMatFee = sumVeripMatFee;
	}

	@Column(name = "SUMVERIPREMNANT", precision=14)
	public BigDecimal getSumVeripRemnant() {
		return this.sumVeripRemnant;
	}

	public void setSumVeripRemnant(BigDecimal sumVeripRemnant) {
		this.sumVeripRemnant = sumVeripRemnant;
	}

	@Column(name = "SUMVERIPLOSS", precision=14)
	public BigDecimal getSumVeripLoss() {
		return this.sumVeripLoss;
	}

	public void setSumVeripLoss(BigDecimal sumVeripLoss) {
		this.sumVeripLoss = sumVeripLoss;
	}

	@Column(name = "VERIPHANDLERCODE", length=10)
	public String getVeripHandlerCode() {
		return this.veripHandlerCode;
	}

	public void setVeripHandlerCode(String veripHandlerCode) {
		this.veripHandlerCode = veripHandlerCode;
	}

	@Column(name = "VERIPHANDLERNAME", length=30)
	public String getVeripHandlerName() {
		return this.veripHandlerName;
	}

	public void setVeripHandlerName(String veripHandlerName) {
		this.veripHandlerName = veripHandlerName;
	}

	@Column(name = "VERIPCOM", length=8)
	public String getVeripCom() {
		return this.veripCom;
	}

	public void setVeripCom(String veripCom) {
		this.veripCom = veripCom;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VERIPENDDATE", length=7)
	public Date getVeripEnddate() {
		return this.veripEnddate;
	}

	public void setVeripEnddate(Date veripEnddate) {
		this.veripEnddate = veripEnddate;
	}

	@Column(name = "VERIPRICEFLAG", length=2)
	public String getVeriPriceFlag() {
		return this.veriPriceFlag;
	}

	public void setVeriPriceFlag(String veriPriceFlag) {
		this.veriPriceFlag = veriPriceFlag;
	}

	@Column(name = "UNDERWRITECODE", length=10)
	public String getUnderWriteCode() {
		return this.underWriteCode;
	}

	public void setUnderWriteCode(String underWriteCode) {
		this.underWriteCode = underWriteCode;
	}

	@Column(name = "UNDERWRITENAME", length=30)
	public String getUnderWriteName() {
		return this.underWriteName;
	}

	public void setUnderWriteName(String underWriteName) {
		this.underWriteName = underWriteName;
	}

	@Column(name = "UNDERWITEIDNO", length=20)
	public String getUnderWiteIdNo() {
		return this.underWiteIdNo;
	}

	public void setUnderWiteIdNo(String underWiteIdNo) {
		this.underWiteIdNo = underWiteIdNo;
	}

	@Column(name = "UNDERWRITECOM", length=10)
	public String getUnderWriteCom() {
		return this.underWriteCom;
	}

	public void setUnderWriteCom(String underWriteCom) {
		this.underWriteCom = underWriteCom;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UNDERWRITEENDDATE", length=7)
	public Date getUnderWriteEndDate() {
		return this.underWriteEndDate;
	}

	public void setUnderWriteEndDate(Date underWriteEndDate) {
		this.underWriteEndDate = underWriteEndDate;
	}

	@Column(name = "UNDERWRITEFLAG", length=2)
	public String getUnderWriteFlag() {
		return this.underWriteFlag;
	}

	public void setUnderWriteFlag(String underWriteFlag) {
		this.underWriteFlag = underWriteFlag;
	}

	@Column(name = "SUMVERICOMPFEE", precision=14)
	public BigDecimal getSumVeriCompFee() {
		return this.sumVeriCompFee;
	}

	public void setSumVeriCompFee(BigDecimal sumVeriCompFee) {
		this.sumVeriCompFee = sumVeriCompFee;
	}

	@Column(name = "SUMVERIREPAIRFEE", precision=14)
	public BigDecimal getSumVeriRepairFee() {
		return this.sumVeriRepairFee;
	}

	public void setSumVeriRepairFee(BigDecimal sumVeriRepairFee) {
		this.sumVeriRepairFee = sumVeriRepairFee;
	}

	@Column(name = "SUMVERIOUTFEE", precision=14)
	public BigDecimal getSumVeriOutFee() {
		return this.sumVeriOutFee;
	}

	public void setSumVeriOutFee(BigDecimal sumVeriOutFee) {
		this.sumVeriOutFee = sumVeriOutFee;
	}

	@Column(name = "SUMVERIMATFEE", precision=14)
	public BigDecimal getSumVeriMatFee() {
		return this.sumVeriMatFee;
	}

	public void setSumVeriMatFee(BigDecimal sumVeriMatFee) {
		this.sumVeriMatFee = sumVeriMatFee;
	}

	@Column(name = "SUMVERIREMNANT", precision=14)
	public BigDecimal getSumVeriRemnant() {
		return this.sumVeriRemnant;
	}

	public void setSumVeriRemnant(BigDecimal sumVeriRemnant) {
		this.sumVeriRemnant = sumVeriRemnant;
	}

	@Column(name = "SUMVERILOSSFEE", precision=14)
	public BigDecimal getSumVeriLossFee() {
		return this.sumVeriLossFee;
	}

	public void setSumVeriLossFee(BigDecimal sumVeriLossFee) {
		this.sumVeriLossFee = sumVeriLossFee;
	}

	@Column(name = "SUMVERIRESCUEFEE", precision=14)
	public BigDecimal getSumVeriRescueFee() {
		return this.sumVeriRescueFee;
	}

	public void setSumVeriRescueFee(BigDecimal sumVeriRescueFee) {
		this.sumVeriRescueFee = sumVeriRescueFee;
	}

	@Column(name = "VERIACTUALVALUE", precision=14)
	public BigDecimal getVeriActualValue() {
		return this.veriActualValue;
	}

	public void setVeriActualValue(BigDecimal veriActualValue) {
		this.veriActualValue = veriActualValue;
	}

	@Column(name = "VERIOTHERFEE", precision=14)
	public BigDecimal getVeriOtherFee() {
		return this.veriOtherFee;
	}

	public void setVeriOtherFee(BigDecimal veriOtherFee) {
		this.veriOtherFee = veriOtherFee;
	}

	@Column(name = "SUMVERICHARGEFEE", precision=14)
	public BigDecimal getSumVeriChargeFee() {
		return this.sumVeriChargeFee;
	}

	public void setSumVeriChargeFee(BigDecimal sumVeriChargeFee) {
		this.sumVeriChargeFee = sumVeriChargeFee;
	}
	
	@Column(name = "SUMSUBRISKFEE", precision=14)
	public BigDecimal getSumSubRiskFee() {
		return sumSubRiskFee;
	}

	public void setSumSubRiskFee(BigDecimal sumSubRiskFee) {
		this.sumSubRiskFee = sumSubRiskFee;
	}
	
	@Column(name = "SUMVERISUBRISKFEE", precision=14)
	public BigDecimal getSumVeriSubRiskFee() {
		return sumVeriSubRiskFee;
	}

	public void setSumVeriSubRiskFee(BigDecimal sumVeriSubRiskFee) {
		this.sumVeriSubRiskFee = sumVeriSubRiskFee;
	}

	@Column(name = "RECHECKFLAG", length=1)
	public String getReCheckFlag() {
		return this.reCheckFlag;
	}

	public void setReCheckFlag(String reCheckFlag) {
		this.reCheckFlag = reCheckFlag;
	}

	@Column(name = "RECHECKCODE")
	public String getReCheckCode() {
		return reCheckCode;
	}

	public void setReCheckCode(String reCheckCode) {
		this.reCheckCode = reCheckCode;
	}

	@Column(name = "RECHECKNAME")
	public String getReCheckName() {
		return reCheckName;
	}

	public void setReCheckName(String reCheckName) {
		this.reCheckName = reCheckName;
	}

	@Column(name = "RECHECKIDNO")
	public String getReCheckIdNo() {
		return reCheckIdNo;
	}

	public void setReCheckIdNo(String reCheckIdNo) {
		this.reCheckIdNo = reCheckIdNo;
	}

	@Column(name = "SERIALNO", precision=5, scale=0)
	public Integer getSerialNo() {
		return this.serialNo;
	}

	public void setSerialNo(Integer serialNo) {
		this.serialNo = serialNo;
	}

	@Column(name = "SUBMITSOURCE", length=2)
	public String getSubmitSource() {
		return this.submitSource;
	}

	public void setSubmitSource(String submitSource) {
		this.submitSource = submitSource;
	}

	@Column(name = "DEFLOSSSOURCEFLAG", length=2)
	public String getDeflossSourceFlag() {
		return this.deflossSourceFlag;
	}

	public void setDeflossSourceFlag(String deflossSourceFlag) {
		this.deflossSourceFlag = deflossSourceFlag;
	}

	@Column(name = "RELOSSCARID", precision=12, scale=0)
	public Long getReLossCarId() {
		return this.reLossCarId;
	}

	public void setReLossCarId(Long reLossCarId) {
		this.reLossCarId = reLossCarId;
	}

	@Column(name = "MAKECOM", nullable = false, length=10)
	public String getMakeCom() {
		return this.makeCom;
	}

	public void setMakeCom(String makeCom) {
		this.makeCom = makeCom;
	}

	@Column(name = "COMCODE", length=8)
	public String getComCode() {
		return this.comCode;
	}

	public void setComCode(String comCode) {
		this.comCode = comCode;
	}

	@Column(name = "VALIDFLAG", nullable = false, length=1)
	public String getValidFlag() {
		return this.validFlag;
	}

	public void setValidFlag(String validFlag) {
		this.validFlag = validFlag;
	}

	@Column(name = "REMARK")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "LOSSSTATE", length=2)
	public String getLossState() {
		return this.lossState;
	}

	public void setLossState(String lossState) {
		this.lossState = lossState;
	}
	
	@Column(name = "RECYCLEFLAG")
	public String getRecycleFlag() {
		return recycleFlag;
	}
	
	public void setRecycleFlag(String recycleFlag) {
		this.recycleFlag = recycleFlag;
	}
	
	@Column(name = "LOSSFEETYPE")
	public String getLossFeeType() {
		return lossFeeType;
	}

	public void setLossFeeType(String lossFeeType) {
		this.lossFeeType = lossFeeType;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DEFENDDATE", length=7)
	public Date getDefEndDate() {
		return this.defEndDate;
	}

	public void setDefEndDate(Date defEndDate) {
		this.defEndDate = defEndDate;
	}

	@Column(name = "AUDITSTATUS", length=30)
	public String getAuditstatus() {
		return this.auditstatus;
	}

	public void setAuditstatus(String auditstatus) {
		this.auditstatus = auditstatus;
	}
	
	@Column(name = "NODECODE", length=30)
	public String getNodeCode() {
		return nodeCode;
	}
	
	public void setNodeCode(String nodeCode) {
		this.nodeCode = nodeCode;
	}
	
	@Column(name = "FLOWFLAG" )
	public String getFlowFlag() {
		return flowFlag;
	}

	public void setFlowFlag(String flowFlag) {
		this.flowFlag = flowFlag;
	}
	
	@Column(name = "VERIFYLEVEL")
	public Integer getVerifyLevel() {
		return verifyLevel;
	}

	public void setVerifyLevel(Integer verifyLevel) {
		this.verifyLevel = verifyLevel;
	}
	
	@Column(name = "MAXLEVEL")
	public Integer getMaxLevel() {
		return maxLevel;
	}

	public void setMaxLevel(Integer maxLevel) {
		this.maxLevel = maxLevel;
	}
	
	@Column(name = "VERIPIDNO", length=20)
	public String getVeripidno() {
		return this.veripidno;
	}

	public void setVeripidno(String veripidno) {
		this.veripidno = veripidno;
	}

	@Column(name = "FLAG", length=10)
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	@Column(name = "CREATEUSER", length=10)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATETIME", length=7)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpLDlossCarMainHis")
	public List<PrpLDlossCarSubRiskHis> getPrpLDlossCarSubRiskHises() {
		return this.prpLDlossCarSubRiskHises;
	}

	public void setPrpLDlossCarSubRiskHises(List<PrpLDlossCarSubRiskHis> prpLDlossCarSubRiskHises) {
		this.prpLDlossCarSubRiskHises = prpLDlossCarSubRiskHises;
	}

    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpLDlossCarMainHis")
	public List<PrpLDlossCarRepairHis> getPrpLDlossCarRepairHises() {
		return this.prpLDlossCarRepairHises;
	}

	public void setPrpLDlossCarRepairHises(List<PrpLDlossCarRepairHis> prpLDlossCarRepairHises) {
		this.prpLDlossCarRepairHises = prpLDlossCarRepairHises;
	}

    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpLDlossCarMainHis")
	public List<PrpLDlossCarMaterialHis> getPrpLDlossCarMaterialHises() {
		return this.prpLDlossCarMaterialHises;
	}

	public void setPrpLDlossCarMaterialHises(List<PrpLDlossCarMaterialHis> prpLDlossCarMaterialHises) {
		this.prpLDlossCarMaterialHises = prpLDlossCarMaterialHises;
	}

    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpLDlossCarMainHis")
	public List<PrpLDlossCarCompHis> getPrpLDlossCarCompHises() {
		return this.prpLDlossCarCompHises;
	}

	public void setPrpLDlossCarCompHises(List<PrpLDlossCarCompHis> prpLDlossCarCompHises) {
		this.prpLDlossCarCompHises = prpLDlossCarCompHises;
	}
	
	@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpLDlossCarMainHis")
	public List<PrpLLossRepairSumInfoHis> getPrpLLossRepairSumInfoHises() {
		return PrpLLossRepairSumInfoHises;
	}

	public void setPrpLLossRepairSumInfoHises(
			List<PrpLLossRepairSumInfoHis> prpLLossRepairSumInfoHises) {
		PrpLLossRepairSumInfoHises = prpLLossRepairSumInfoHises;
	}
	
	@OneToOne(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpLDlossCarMainHis")
	public PrplLossRuleHis getPrplLossRuleHis() {
		return prplLossRuleHis;
	}

	public void setPrplLossRuleHis(PrplLossRuleHis prplLossRuleHis) {
		this.prplLossRuleHis = prplLossRuleHis;
	}

	@Column(name = "REPAIRTYPE", length=5)
	public String getRepairType() {
		return repairType;
	}

	public void setRepairType(String repairType) {
		this.repairType = repairType;
	}

	@Column(name = "OFFLINEHANDING", length=2)
	public String getOffLineHanding() {
		return offLineHanding;
	}

	public void setOffLineHanding(String offLineHanding) {
		this.offLineHanding = offLineHanding;
	}

	@Column(name = "PHOTOSTATUS", length=20)
	public String getPhotoStatus() {
		return photoStatus;
	}

	public void setPhotoStatus(String photoStatus) {
		this.photoStatus = photoStatus;
	}

	@Column(name = "SUMVERIMANAGE", precision=12, scale=0)
	public BigDecimal getSumVeriManage() {
		return sumVeriManage;
	}

	public void setSumVeriManage(BigDecimal sumVeriManage) {
		this.sumVeriManage = sumVeriManage;
	}

	@Column(name = "SUMVERIPMANAGE", precision=12, scale=0)
	public BigDecimal getSumVeriPManage() {
		return sumVeriPManage;
	}

	public void setSumVeriPManage(BigDecimal sumVeriPManage) {
		this.sumVeriPManage = sumVeriPManage;
	}

	@Column(name = "SUMVERIPSELFPAY", precision=12, scale=0)
	public BigDecimal getSumVeripSelfpay() {
		return sumVeripSelfpay;
	}

	public void setSumVeripSelfpay(BigDecimal sumVeripSelfpay) {
		this.sumVeripSelfpay = sumVeripSelfpay;
	}

	@Column(name = "SUMVERISELFPAY", precision=12, scale=0)
	public BigDecimal getSumVeriSelfpay() {
		return sumVeriSelfpay;
	}

	public void setSumVeriSelfpay(BigDecimal sumVeriSelfpay) {
		this.sumVeriSelfpay = sumVeriSelfpay;
	}

	@Column(name = "SUMVERIPDEROGATION", precision=12, scale=0)
	public BigDecimal getSumVeripDerogation() {
		return sumVeripDerogation;
	}

	public void setSumVeripDerogation(BigDecimal sumVeripDerogation) {
		this.sumVeripDerogation = sumVeripDerogation;
	}

	@Column(name = "SUMVERIDEROGATION", precision=12, scale=0)
	public BigDecimal getSumVeriDerogation() {
		return sumVeriDerogation;
	}

	public void setSumVeriDerogation(BigDecimal sumVeriDerogation) {
		this.sumVeriDerogation = sumVeriDerogation;
	}
	
	@Column(name = "SUMMANAGEFEE", precision=12, scale=2)
	public BigDecimal getSumManageFee() {
		return sumManageFee;
	}

	public void setSumManageFee(BigDecimal sumManageFee) {
		this.sumManageFee = sumManageFee;
	}

	@Column(name = "SUMSELFPAYFEE", precision=12, scale=2)
	public BigDecimal getSumSelfPayFee() {
		return sumSelfPayFee;
	}

	public void setSumSelfPayFee(BigDecimal sumSelfPayFee) {
		this.sumSelfPayFee = sumSelfPayFee;
	}

	@Column(name = "SUMOUTERFEE", precision=12, scale=2)
	public BigDecimal getSumOuterFee() {
		return sumOuterFee;
	}

	public void setSumOuterFee(BigDecimal sumOuterFee) {
		this.sumOuterFee = sumOuterFee;
	}

	@Column(name = "SUMDEROGATIONFEE", precision=12, scale=2)
	public BigDecimal getSumDerogationFee() {
		return sumDerogationFee;
	}

	public void setSumDerogationFee(BigDecimal sumDerogationFee) {
		this.sumDerogationFee = sumDerogationFee;
	}
}
