package ins.sino.claim.powerGridCarClaimLog.po;

//Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!
import java.util.Date;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
* POJO Class GDPowerGridCarClaimLog
*/
@Entity
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "GDPOWERGRIDCARCLAIMLOG")
public class GDPowerGridCarClaimLog implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private String id;
	private Date sendTime;
	private String sendJson;
	private String responseJson;
	private Date returnTime;
	private String responseCode;
	private String errorMessage;
	private Long cost;
	private String reqtypeCode;
	private String reqtypeName;

	@Id
	@Column(name = "ID", unique = true, nullable = false, length=100)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SENDTIME", length=7)
	public Date getSendTime() {
		return sendTime;
	}

	public void setSendTime(Date sendTime) {
		this.sendTime = sendTime;
	}

	@Column(name = "SENDJSON")
	@Basic(fetch = FetchType.LAZY)
	@Lob
	public String getSendJson() {
		return sendJson;
	}

	public void setSendJson(String sendJson) {
		this.sendJson = sendJson;
	}

	@Column(name = "RESPONSEJSON")
	@Basic(fetch = FetchType.LAZY)
	@Lob
	public String getResponseJson() {
		return responseJson;
	}

	public void setResponseJson(String responseJson) {
		this.responseJson = responseJson;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RETURNTIME", length=7)
	public Date getReturnTime() {
		return returnTime;
	}

	public void setReturnTime(Date returnTime) {
		this.returnTime = returnTime;
	}

	@Column(name = "RESPONSECODE", length=10)
	public String getResponseCode() {
		return responseCode;
	}

	public void setResponseCode(String responseCode) {
		this.responseCode = responseCode;
	}

	@Column(name = "ERRORMESSAGE")
	public String getErrorMessage() {
		return errorMessage;
	}

	public void setErrorMessage(String errorMessage) {
		this.errorMessage = errorMessage;
	}

	@Column(name = "COST", precision=10, scale=0)
	public Long getCost() {
		return cost;
	}

	public void setCost(Long cost) {
		this.cost = cost;
	}

	@Column(name = "REQTYPECODE", length=20)
	public String getReqtypeCode() {
		return reqtypeCode;
	}

	public void setReqtypeCode(String reqtypeCode) {
		this.reqtypeCode = reqtypeCode;
	}

	@Column(name = "REQTYPENAME")
	public String getReqtypeName() {
		return reqtypeName;
	}

	public void setReqtypeName(String reqtypeName) {
		this.reqtypeName = reqtypeName;
	}
}
