package ins.sino.claimcar.other.po;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!
import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * POJO Class PrpLAssessorFee
 */
@Entity
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@TableGenerator(name = "utiSequence", table = "UTISEQUENCE", pkColumnName = "GenName", valueColumnName = "GenValue", pkColumnValue = "PRPLASSESSORFEE_PK", allocationSize = 10)
@Table(name = "PRPLASSESSORFEE")
public class PrpLAssessorFee implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long id;
	private PrpLAssessorMain prpLAssessorMain;
	private String registNo;
	private String policyNo;
	private String claimNo;
	private String compensateNo;
	private String kindCode;
	private String insurecode;
	private String insurename;
	private BigDecimal payAmount;
	private BigDecimal amount;
	private String taskIds;
	private String taskDetail;
	private String taskStatus;
	private String payStatus;
	private Date payTime;
	private String createUser;
	private Date createTime;
	private String updateUser;
	private Date updateTime;
	private String invoiceType;
	private String addTaxRate;
	private String addTaxValue;
	private String noTaxValue;
	private Long bankId;//公估费银行Id
	private String remark;
	private String endNo;//结算单号
	private String linkBillNo;//发票号与发票代码

	@Id
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "utiSequence")
	@Column(name = "ID", unique = true, nullable = false, precision = 12, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ASSESSORID", nullable = false)
	public PrpLAssessorMain getPrpLAssessorMain() {
		return this.prpLAssessorMain;
	}

	public void setPrpLAssessorMain(PrpLAssessorMain prpLAssessorMain) {
		this.prpLAssessorMain = prpLAssessorMain;
	}

	@Column(name = "REGISTNO", length = 25)
	public String getRegistNo() {
		return this.registNo;
	}

	public void setRegistNo(String registNo) {
		this.registNo = registNo;
	}

	@Column(name = "POLICYNO", length = 25)
	public String getPolicyNo() {
		return this.policyNo;
	}

	public void setPolicyNo(String policyNo) {
		this.policyNo = policyNo;
	}

	@Column(name = "CLAIMNO", length = 25)
	public String getClaimNo() {
		return this.claimNo;
	}

	public void setClaimNo(String claimNo) {
		this.claimNo = claimNo;
	}

	@Column(name = "COMPENSATENO", length = 25)
	public String getCompensateNo() {
		return compensateNo;
	}

	
	public void setCompensateNo(String compensateNo) {
		this.compensateNo = compensateNo;
	}

	@Column(name = "KINDCODE", length = 10)
	public String getKindCode() {
		return this.kindCode;
	}

	public void setKindCode(String kindCode) {
		this.kindCode = kindCode;
	}

	@Column(name = "INSURECODE", length = 30)
	public String getInsurecode() {
		return this.insurecode;
	}

	public void setInsurecode(String insurecode) {
		this.insurecode = insurecode;
	}

	@Column(name = "INSURENAME", length = 30)
	public String getInsurename() {
		return this.insurename;
	}

	public void setInsurename(String insurename) {
		this.insurename = insurename;
	}

	@Column(name = "PAYAMOUNT", precision = 10)
	public BigDecimal getPayAmount() {
		return this.payAmount;
	}

	public void setPayAmount(BigDecimal payAmount) {
		this.payAmount = payAmount;
	}

	@Column(name = "AMOUNT", precision = 10)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "TASKIDS", length = 150)
	public String getTaskIds() {
		return taskIds;
	}

	public void setTaskIds(String taskIds) {
		this.taskIds = taskIds;
	}

	@Column(name = "TASKDETAIL", length = 150)
	public String getTaskDetail() {
		return taskDetail;
	}

	
	public void setTaskDetail(String taskDetail) {
		this.taskDetail = taskDetail;
	}

	@Column(name = "TASKSTATUS", length = 2)
	public String getTaskStatus() {
		return taskStatus;
	}

	
	public void setTaskStatus(String taskStatus) {
		this.taskStatus = taskStatus;
	}

	@Column(name = "CREATEUSER", length = 10)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATETIME", length = 7)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "UPDATEUSER", length = 10)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATETIME", length = 7)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
	
	@Column(name = "PAYSTATUS")
	public String getPayStatus() {
		return payStatus;
	}

	public void setPayStatus(String payStatus) {
		this.payStatus = payStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PAYTIME", length = 7)
	public Date getPayTime() {
		return payTime;
	}

	public void setPayTime(Date payTime) {
		this.payTime = payTime;
	}
	
	@Column(name = "INVOICETYPE", length=10)
	public String getInvoiceType() {
		return invoiceType;
	}

	public void setInvoiceType(String invoiceType) {
		this.invoiceType = invoiceType;
	}
	@Column(name = "ADDTAXRATE", length=10)
	public String getAddTaxRate() {
		return addTaxRate;
	}

	public void setAddTaxRate(String addTaxRate) {
		this.addTaxRate = addTaxRate;
	}
	@Column(name = "ADDTAXVALUE", length=10)
	public String getAddTaxValue() {
		return addTaxValue;
	}

	public void setAddTaxValue(String addTaxValue) {
		this.addTaxValue = addTaxValue;
	}
	@Column(name = "NOTAXVALUE", length=10)
	public String getNoTaxValue() {
		return noTaxValue;
	}

	public void setNoTaxValue(String noTaxValue) {
		this.noTaxValue = noTaxValue;
	}


	

	@Column(name = "BANKID", precision=15)
	public Long getBankId() {
		return bankId;
	}

	public void setBankId(Long bankId) {
		this.bankId = bankId;
	}
	
	@Column(name = "REMARK", length=2010)
	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}
	@Column(name = "ENDNO", length = 40)
	public String getEndNo() {
		return endNo;
	}

	public void setEndNo(String endNo) {
		this.endNo = endNo;
	}
	
	@Column(name = "LINKBILLNO", length = 100)
	public String getLinkBillNo() {
		return linkBillNo;
	}

	public void setLinkBillNo(String linkBillNo) {
		this.linkBillNo = linkBillNo;
	}

}
