package ins.sino.claimcar.regist.vo;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!
import java.util.Date;


/**
 * Vo Base Class of PO PrpLRegistCarLoss
 */ 
public class PrpLRegistCarLossVoBase implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Long id;
	private String licenseNo;
	private String frameNo;
	private String brandName;
	private String licenseType;
	private String lossparty;
	private String inscompanybi;
	private String brand;
	private String repairCode;
	private String repairName;
	private String inscompanyci;
	private String inspolicybi;
	private String inspolicyci;
	private String thriddrivername;
	private String thriddriversex;
	private String thriddrivingno;
	private String thriddriverphone;
	private String losspart;
	private String lossremark;
	private String validflag;
	private String flag;
	private String remark;
	private String createUser;
	private Date createTime;
	private String updateUser;
	private Date updateTime;

    protected PrpLRegistCarLossVoBase() {
	
    }

    
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getLicenseNo() {
		return this.licenseNo;
	}

	public void setLicenseNo(String licenseNo) {
		this.licenseNo = licenseNo;
	}

	public String getFrameNo() {
		return this.frameNo;
	}

	public void setFrameNo(String frameNo) {
		this.frameNo = frameNo;
	}

	public String getBrandName() {
		return this.brandName;
	}

	public void setBrandName(String brandName) {
		this.brandName = brandName;
	}

	public String getLicenseType() {
		return this.licenseType;
	}

	public void setLicenseType(String licenseType) {
		this.licenseType = licenseType;
	}

	public String getLossparty() {
		return this.lossparty;
	}

	public void setLossparty(String lossparty) {
		this.lossparty = lossparty;
	}

	public String getInscompanybi() {
		return this.inscompanybi;
	}

	public void setInscompanybi(String inscompanybi) {
		this.inscompanybi = inscompanybi;
	}

	public String getInscompanyci() {
		return this.inscompanyci;
	}

	public void setInscompanyci(String inscompanyci) {
		this.inscompanyci = inscompanyci;
	}

	public String getInspolicybi() {
		return this.inspolicybi;
	}

	public void setInspolicybi(String inspolicybi) {
		this.inspolicybi = inspolicybi;
	}

	public String getInspolicyci() {
		return this.inspolicyci;
	}

	public void setInspolicyci(String inspolicyci) {
		this.inspolicyci = inspolicyci;
	}

	public String getThriddrivername() {
		return this.thriddrivername;
	}

	public void setThriddrivername(String thriddrivername) {
		this.thriddrivername = thriddrivername;
	}

	public String getThriddriversex() {
		return this.thriddriversex;
	}

	public void setThriddriversex(String thriddriversex) {
		this.thriddriversex = thriddriversex;
	}

	public String getThriddrivingno() {
		return this.thriddrivingno;
	}

	public void setThriddrivingno(String thriddrivingno) {
		this.thriddrivingno = thriddrivingno;
	}

	public String getThriddriverphone() {
		return this.thriddriverphone;
	}

	public void setThriddriverphone(String thriddriverphone) {
		this.thriddriverphone = thriddriverphone;
	}

	public String getLosspart() {
		return this.losspart;
	}

	public void setLosspart(String losspart) {
		this.losspart = losspart;
	}

	public String getLossremark() {
		return this.lossremark;
	}

	public void setLossremark(String lossremark) {
		this.lossremark = lossremark;
	}

	public String getValidflag() {
		return this.validflag;
	}

	public void setValidflag(String validflag) {
		this.validflag = validflag;
	}

	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}


	
	public String getBrand() {
		return brand;
	}


	
	public void setBrand(String brand) {
		this.brand = brand;
	}


	
	public String getRepairCode() {
		return repairCode;
	}


	
	public void setRepairCode(String repairCode) {
		this.repairCode = repairCode;
	}


	
	public String getRepairName() {
		return repairName;
	}


	
	public void setRepairName(String repairName) {
		this.repairName = repairName;
	}
}
