package ins.sino.claimcar.claim.vo;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Vo Base Class of PO PrpLPadPayMain
 */
public class PrpLPadPayMainVoBase implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long id;
	private String claimNo;
	private String registNo;
	private String compensateNo;
	private String policyNo;
	private String policeNoticeNo;
	private String policeName;
	private String policePhone;
	private String noticeCom;
	private Date noticeDate;
	private BigDecimal ci_MedFee;
	private BigDecimal ci_DisFee;
	private String validFlag;
	private String flag;
	private String remark;
	private String createUser;
	private Date createTime;
	private String updateUser;
	private Date updateTime;
	private String underwriteFlag;// 核赔标志
	private String underwriteUser;// 核赔处理人
	private Date underwriteDate;// 核赔通过时间
	private String isCompdeDuct;// 是否已理算扣减
	private String comCode;
	/** 平安赔付次数 */
	private Integer caseTimes;
	/** 平安垫付次数 */
	private Integer advanceTimes;
	private List<PrpLPadPayPersonVo> prpLPadPayPersons = new ArrayList<PrpLPadPayPersonVo>(0);

	protected PrpLPadPayMainVoBase(){

	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getClaimNo() {
		return this.claimNo;
	}

	public void setClaimNo(String claimNo) {
		this.claimNo = claimNo;
	}

	public String getRegistNo() {
		return this.registNo;
	}

	public void setRegistNo(String registNo) {
		this.registNo = registNo;
	}

	public String getCompensateNo() {
		return this.compensateNo;
	}

	public void setCompensateNo(String compensateNo) {
		this.compensateNo = compensateNo;
	}

	public String getPolicyNo() {
		return this.policyNo;
	}

	public void setPolicyNo(String policyNo) {
		this.policyNo = policyNo;
	}

	public String getPoliceNoticeNo() {
		return this.policeNoticeNo;
	}

	public void setPoliceNoticeNo(String policeNoticeNo) {
		this.policeNoticeNo = policeNoticeNo;
	}

	public String getPoliceName() {
		return this.policeName;
	}

	public void setPoliceName(String policeName) {
		this.policeName = policeName;
	}

	public String getPolicePhone() {
		return this.policePhone;
	}

	public void setPolicePhone(String policePhone) {
		this.policePhone = policePhone;
	}

	public String getNoticeCom() {
		return this.noticeCom;
	}

	public void setNoticeCom(String noticeCom) {
		this.noticeCom = noticeCom;
	}

	public Date getNoticeDate() {
		return this.noticeDate;
	}

	public void setNoticeDate(Date noticeDate) {
		this.noticeDate = noticeDate;
	}

	public String getValidFlag() {
		return this.validFlag;
	}

	public void setValidFlag(String validFlag) {
		this.validFlag = validFlag;
	}

	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public List<PrpLPadPayPersonVo> getPrpLPadPayPersons() {
		return this.prpLPadPayPersons;
	}

	public void setPrpLPadPayPersons(List<PrpLPadPayPersonVo> prpLPadPayPersons) {
		this.prpLPadPayPersons = prpLPadPayPersons;
	}

	public BigDecimal getCi_MedFee() {
		return this.ci_MedFee;
	}

	public void setCi_MedFee(BigDecimal ci_MedFee) {
		this.ci_MedFee = ci_MedFee;
	}

	public BigDecimal getCi_DisFee() {
		return this.ci_DisFee;
	}

	public void setCi_DisFee(BigDecimal ci_DisFee) {
		this.ci_DisFee = ci_DisFee;
	}

	public String getUnderwriteFlag() {
		return underwriteFlag;
	}

	public void setUnderwriteFlag(String underwriteFlag) {
		this.underwriteFlag = underwriteFlag;
	}

	public String getUnderwriteUser() {
		return underwriteUser;
	}

	public void setUnderwriteUser(String underwriteUser) {
		this.underwriteUser = underwriteUser;
	}

	public Date getUnderwriteDate() {
		return underwriteDate;
	}

	public void setUnderwriteDate(Date underwriteDate) {
		this.underwriteDate = underwriteDate;
	}

	public String getIsCompdeDuct() {
		return isCompdeDuct;
	}

	public void setIsCompdeDuct(String isCompdeDuct) {
		this.isCompdeDuct = isCompdeDuct;
	}

	/**
	 * @return 返回 comCode。
	 */
	public String getComCode() {
		return this.comCode;
	}

	/**
	 * @param comCode 要设置的 comCode。
	 */
	public void setComCode(String comCode) {
		this.comCode = comCode;
	}

	public Integer getCaseTimes() {
		return caseTimes;
	}

	public void setCaseTimes(Integer caseTimes) {
		this.caseTimes = caseTimes;
	}

	public Integer getAdvanceTimes() {
		return advanceTimes;
	}

	public void setAdvanceTimes(Integer advanceTimes) {
		this.advanceTimes = advanceTimes;
	}
}
