package ins.sino.claimcar.claim.vo;

import java.math.BigDecimal;
import java.util.Date;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!

/**
 * Vo Base Class of PO PrpLPadPayPerson
 */
public class PrpLPadPayPersonVoBase implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long id;
	private PrpLPadPayMainVo prpLPadPayMain;
	private String personName;
	private Integer personAge;
	private String personSex;
	private String personType;
	private String injuryType;
	private String personAddress;
	private String licenseNo;
	private String hospitalProvince;
	private String hospitalCity;
	private String hospitalCode;
	private String hospitalName;
	private String personIdfNo;
	private String feeNameCode;
	private String feeUpperCode;
	private BigDecimal costSum;
	private String riskCode;
	private String payeeName;
	private String otherFlag;
	private String otherCause;
	private String accountNo;
	private String bankName;
	private String flag;
	private String remark;
	private Long payeeId;
	private String payStatus;
	private String sendPayStatus;
	private String serialNo;
	private Date payTime;
	private String payObjectKind;
	private String summary;
	private String settleNo;
	/** 平安支付信息主键 */
	private String idClmPaymentResult;
	protected PrpLPadPayPersonVoBase(){

	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public PrpLPadPayMainVo getPrpLPadPayMain() {
		return this.prpLPadPayMain;
	}

	public void setPrpLPadPayMain(PrpLPadPayMainVo prpLPadPayMain) {
		this.prpLPadPayMain = prpLPadPayMain;
	}

	public String getPersonName() {
		return this.personName;
	}

	public void setPersonName(String personName) {
		this.personName = personName;
	}

	public Integer getPersonAge() {
		return this.personAge;
	}

	public void setPersonAge(Integer personAge) {
		this.personAge = personAge;
	}

	public String getPersonSex() {
		return this.personSex;
	}

	public void setPersonSex(String personSex) {
		this.personSex = personSex;
	}

	public String getPersonType() {
		return this.personType;
	}

	public void setPersonType(String personType) {
		this.personType = personType;
	}

	public String getInjuryType() {
		return this.injuryType;
	}

	public void setInjuryType(String injuryType) {
		this.injuryType = injuryType;
	}

	public String getPersonAddress() {
		return this.personAddress;
	}

	public void setPersonAddress(String personAddress) {
		this.personAddress = personAddress;
	}

	public String getLicenseNo() {
		return this.licenseNo;
	}

	public void setLicenseNo(String licenseNo) {
		this.licenseNo = licenseNo;
	}

	public String getHospitalProvince() {
		return this.hospitalProvince;
	}

	public void setHospitalProvince(String hospitalProvince) {
		this.hospitalProvince = hospitalProvince;
	}

	public String getHospitalCity() {
		return this.hospitalCity;
	}

	public void setHospitalCity(String hospitalCity) {
		this.hospitalCity = hospitalCity;
	}

	public String getHospitalCode() {
		return this.hospitalCode;
	}

	public void setHospitalCode(String hospitalCode) {
		this.hospitalCode = hospitalCode;
	}

	public String getHospitalName() {
		return this.hospitalName;
	}

	public void setHospitalName(String hospitalName) {
		this.hospitalName = hospitalName;
	}

	public String getPersonIdfNo() {
		return this.personIdfNo;
	}

	public void setPersonIdfNo(String personIdfNo) {
		this.personIdfNo = personIdfNo;
	}

	public String getRiskCode() {
		return this.riskCode;
	}

	public void setRiskCode(String riskCode) {
		this.riskCode = riskCode;
	}

	public String getPayeeName() {
		return this.payeeName;
	}

	public void setPayeeName(String payeeName) {
		this.payeeName = payeeName;
	}

	public String getOtherFlag() {
		return this.otherFlag;
	}

	public void setOtherFlag(String otherFlag) {
		this.otherFlag = otherFlag;
	}

	public String getOtherCause() {
		return this.otherCause;
	}

	public void setOtherCause(String otherCause) {
		this.otherCause = otherCause;
	}

	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public BigDecimal getCostSum() {
		return this.costSum;
	}

	public void setCostSum(BigDecimal costSum) {
		this.costSum = costSum;
	}

	public String getAccountNo() {
		return this.accountNo;
	}

	public void setAccountNo(String accountNo) {
		this.accountNo = accountNo;
	}

	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	public String getFeeNameCode() {
		return this.feeNameCode;
	}

	public void setFeeNameCode(String feeNameCode) {
		this.feeNameCode = feeNameCode;
	}

	public String getFeeUpperCode() {
		return this.feeUpperCode;
	}

	public void setFeeUpperCode(String feeUpperCode) {
		this.feeUpperCode = feeUpperCode;
	}

	public Long getPayeeId() {
		return this.payeeId;
	}

	public void setPayeeId(Long payeeId) {
		this.payeeId = payeeId;
	}

	public String getPayStatus() {
		return this.payStatus;
	}

	public void setPayStatus(String payStatus) {
		this.payStatus = payStatus;
	}

	public String getSendPayStatus() {
		return this.sendPayStatus;
	}

	public void setSendPayStatus(String sendPayStatus) {
		this.sendPayStatus = sendPayStatus;
	}

	/**
	 * @return 返回 serialNo。
	 */
	public String getSerialNo() {
		return this.serialNo;
	}
	
	/**
	 * @param serialNo 要设置的 serialNo。
	 */
	public void setSerialNo(String serialNo) {
		this.serialNo = serialNo;
	}

	public Date getPayTime() {
		return payTime;
	}

	public void setPayTime(Date payTime) {
		this.payTime = payTime;
	}

    public String getPayObjectKind() {
        return payObjectKind;
    }

    public void setPayObjectKind(String payObjectKind) {
        this.payObjectKind = payObjectKind;
    }

	public String getSummary() {
		return summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	public String getSettleNo() {
		return settleNo;
	}

	public void setSettleNo(String settleNo) {
		this.settleNo = settleNo;
	}

	public String getIdClmPaymentResult() { return idClmPaymentResult; }

	public void setIdClmPaymentResult(String idClmPaymentResult) { this.idClmPaymentResult = idClmPaymentResult; }
}
