package ins.sino.claimcar.claim.vo;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;


/**
 * Vo Base Class of PO PrplReplevyMain
 */ 
public class PrplReplevyMainVoBase implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Long id;
	private String registNo;
	private String compensateNo;
	private String claimNo;
	private String policyNo;
	private String replevyType;
	private String repleviedName;
	private Date replevyDate;
	private Date endDate;
	private String entrustComName;
	private String replevyReason;
	private String progress;
	private BigDecimal sumPlanReplevy;
	private BigDecimal sumRealReplevy;
	private BigDecimal sumReplevyFee;
	private String replevyText;
	private String makeCom;
	private String comCode;
	private String handlerCode;
	private String createUser;
	private Date createTime;
	private String updateUser;
	private Date updateTime;
	private String replevySource;
	private String riskCode;
	private String underWriteFlag;
	private List<PrplReplevyDetailVo> prplReplevyDetails = new ArrayList<PrplReplevyDetailVo>(0);

    protected PrplReplevyMainVoBase() {
	
    }

    
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getRegistNo() {
		return this.registNo;
	}

	public void setRegistNo(String registNo) {
		this.registNo = registNo;
	}

	public String getCompensateNo() {
		return this.compensateNo;
	}

	public void setCompensateNo(String compensateNo) {
		this.compensateNo = compensateNo;
	}

	public String getClaimNo() {
		return this.claimNo;
	}

	public void setClaimNo(String claimNo) {
		this.claimNo = claimNo;
	}

	public String getPolicyNo() {
		return this.policyNo;
	}

	public void setPolicyNo(String policyNo) {
		this.policyNo = policyNo;
	}

	public String getReplevyType() {
		return this.replevyType;
	}

	public void setReplevyType(String replevyType) {
		this.replevyType = replevyType;
	}

	public String getRepleviedName() {
		return this.repleviedName;
	}

	public void setRepleviedName(String repleviedName) {
		this.repleviedName = repleviedName;
	}

	public Date getReplevyDate() {
		return this.replevyDate;
	}

	public void setReplevyDate(Date replevyDate) {
		this.replevyDate = replevyDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getEntrustComName() {
		return this.entrustComName;
	}

	public void setEntrustComName(String entrustComName) {
		this.entrustComName = entrustComName;
	}

	public String getReplevyReason() {
		return this.replevyReason;
	}

	public void setReplevyReason(String replevyReason) {
		this.replevyReason = replevyReason;
	}

	public String getProgress() {
		return this.progress;
	}

	public void setProgress(String progress) {
		this.progress = progress;
	}

	public BigDecimal getSumPlanReplevy() {
		return this.sumPlanReplevy;
	}

	public void setSumPlanReplevy(BigDecimal sumPlanReplevy) {
		this.sumPlanReplevy = sumPlanReplevy;
	}

	public BigDecimal getSumRealReplevy() {
		return this.sumRealReplevy;
	}

	public void setSumRealReplevy(BigDecimal sumRealReplevy) {
		this.sumRealReplevy = sumRealReplevy;
	}

	public BigDecimal getSumReplevyFee() {
		return this.sumReplevyFee;
	}

	public void setSumReplevyFee(BigDecimal sumReplevyFee) {
		this.sumReplevyFee = sumReplevyFee;
	}

	public String getReplevyText() {
		return this.replevyText;
	}

	public void setReplevyText(String replevyText) {
		this.replevyText = replevyText;
	}

	public String getMakeCom() {
		return this.makeCom;
	}

	public void setMakeCom(String makeCom) {
		this.makeCom = makeCom;
	}

	public String getComCode() {
		return this.comCode;
	}

	public void setComCode(String comCode) {
		this.comCode = comCode;
	}

	public String getHandlerCode() {
		return this.handlerCode;
	}

	public void setHandlerCode(String handlerCode) {
		this.handlerCode = handlerCode;
	}

	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public List<PrplReplevyDetailVo> getPrplReplevyDetails() {
		return this.prplReplevyDetails;
	}

	public void setPrplReplevyDetails(List<PrplReplevyDetailVo> prplReplevyDetails) {
		this.prplReplevyDetails = prplReplevyDetails;
	}


	public String getReplevySource() {
		return replevySource;
	}


	public void setReplevySource(String replevySource) {
		this.replevySource = replevySource;
	}


	public String getRiskCode() {
		return riskCode;
	}


	public void setRiskCode(String riskCode) {
		this.riskCode = riskCode;
	}


	public String getUnderWriteFlag() {
		return underWriteFlag;
	}


	public void setUnderWriteFlag(String underWriteFlag) {
		this.underWriteFlag = underWriteFlag;
	}
}
