package ins.sino.claimcar.base.po;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * POJO Class PrpLFourSShopInfo
 */
@Entity
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@TableGenerator(name = "utiSequence", table = "UTISEQUENCE", pkColumnName = "GenName", valueColumnName = "GenValue", pkColumnValue = "PRPLFOURSSHOPINFO_PK", allocationSize = 10)
@Table(name = "PRPLFOURSSHOPINFO")
public class PrpLFourSShopInfo implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Long id;
	private Date startTime;
	private String foursLevel;
	private String blanketInsuraCode;
	private String businessLinkManPhone;
	private String category;
	private String comCode;
	private String comName;
	private String factoryCode;
	private String factoryName;
	private String pushRepairPhone;
	private String pushRepairLinkMan;
	private String pushRepairAddress;
	private String sendRepair;
	private String workingHours;
	private String deflossLimit;
	private String specialCommitMent;
	private String carBrandCode;
	private String carBrandName;
	private String remark;
	private String fourSShopCode;
	private String fourSShopName;
	private String areaCode;
	private String busiNatureNo;
	private String busiNatureName;
	private String validStatus;
	private String carBrands;

	@Id
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "utiSequence")
	@Column(name = "ID", unique = true, nullable = false, scale=0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "STARTTIME", length=7)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Column(name = "FOURSLEVEL", length=2)
	public String getFoursLevel() {
		return this.foursLevel;
	}

	public void setFoursLevel(String foursLevel) {
		this.foursLevel = foursLevel;
	}

	@Column(name = "BLANKETINSURACODE", length=30)
	public String getBlanketInsuraCode() {
		return this.blanketInsuraCode;
	}

	public void setBlanketInsuraCode(String blanketInsuraCode) {
		this.blanketInsuraCode = blanketInsuraCode;
	}

	@Column(name = "BUSINESSLINKMANPHONE", length=15)
	public String getBusinessLinkManPhone() {
		return this.businessLinkManPhone;
	}

	public void setBusinessLinkManPhone(String businessLinkManPhone) {
		this.businessLinkManPhone = businessLinkManPhone;
	}

	@Column(name = "CATEGORY", length=5)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "COMCODE", length=15)
	public String getComCode() {
		return this.comCode;
	}

	public void setComCode(String comCode) {
		this.comCode = comCode;
	}

	@Column(name = "COMNAME")
	public String getComName() {
		return this.comName;
	}

	public void setComName(String comName) {
		this.comName = comName;
	}

	@Column(name = "FACTORYCODE", length=30)
	public String getFactoryCode() {
		return this.factoryCode;
	}

	public void setFactoryCode(String factoryCode) {
		this.factoryCode = factoryCode;
	}

	@Column(name = "FACTORYNAME", length=150)
	public String getFactoryName() {
		return this.factoryName;
	}

	public void setFactoryName(String factoryName) {
		this.factoryName = factoryName;
	}

	@Column(name = "PUSHREPAIRPHONE", length=15)
	public String getPushRepairPhone() {
		return this.pushRepairPhone;
	}

	public void setPushRepairPhone(String pushRepairPhone) {
		this.pushRepairPhone = pushRepairPhone;
	}

	@Column(name = "PUSHREPAIRLINKMAN", length=150)
	public String getPushRepairLinkMan() {
		return this.pushRepairLinkMan;
	}

	public void setPushRepairLinkMan(String pushRepairLinkMan) {
		this.pushRepairLinkMan = pushRepairLinkMan;
	}

	@Column(name = "PUSHREPAIRADDRESS")
	public String getPushRepairAddress() {
		return this.pushRepairAddress;
	}

	public void setPushRepairAddress(String pushRepairAddress) {
		this.pushRepairAddress = pushRepairAddress;
	}

	@Column(name = "SENDREPAIR", nullable = false, length=1)
	public String getSendRepair() {
		return this.sendRepair;
	}

	public void setSendRepair(String sendRepair) {
		this.sendRepair = sendRepair;
	}

	@Column(name = "WORKINGHOURS", length=100)
	public String getWorkingHours() {
		return this.workingHours;
	}

	public void setWorkingHours(String workingHours) {
		this.workingHours = workingHours;
	}

	@Column(name = "DEFLOSSLIMIT", length=100)
	public String getDeflossLimit() {
		return this.deflossLimit;
	}

	public void setDeflossLimit(String deflossLimit) {
		this.deflossLimit = deflossLimit;
	}

	@Column(name = "SPECIALCOMMITMENT")
	public String getSpecialCommitMent() {
		return this.specialCommitMent;
	}

	public void setSpecialCommitMent(String specialCommitMent) {
		this.specialCommitMent = specialCommitMent;
	}

	@Column(name = "CARBRANDCODE", length=20)
	public String getCarBrandCode() {
		return this.carBrandCode;
	}

	public void setCarBrandCode(String carBrandCode) {
		this.carBrandCode = carBrandCode;
	}

	@Column(name = "CARBRANDNAME", length=150)
	public String getCarBrandName() {
		return this.carBrandName;
	}

	public void setCarBrandName(String carBrandName) {
		this.carBrandName = carBrandName;
	}

	@Column(name = "REMARK")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "FOURSSHOPCODE", length=30)
	public String getFourSShopCode() {
		return this.fourSShopCode;
	}

	public void setFourSShopCode(String fourSShopCode) {
		this.fourSShopCode = fourSShopCode;
	}

	@Column(name = "FOURSSHOPNAME", length=150)
	public String getFourSShopName() {
		return this.fourSShopName;
	}

	public void setFourSShopName(String fourSShopName) {
		this.fourSShopName = fourSShopName;
	}

	@Column(name = "AREACODE", length=30)
	public String getAreaCode() {
		return this.areaCode;
	}

	public void setAreaCode(String areaCode) {
		this.areaCode = areaCode;
	}

	@Column(name = "BUSINATURENO", length=30)
	public String getBusiNatureNo() {
		return this.busiNatureNo;
	}

	public void setBusiNatureNo(String busiNatureNo) {
		this.busiNatureNo = busiNatureNo;
	}

	@Column(name = "BUSINATURENAME", length=250)
	public String getBusiNatureName() {
		return this.busiNatureName;
	}

	public void setBusiNatureName(String busiNatureName) {
		this.busiNatureName = busiNatureName;
	}

	@Column(name = "VALIDSTATUS", length=1)
	public String getValidStatus() {
		return this.validStatus;
	}

	public void setValidStatus(String validStatus) {
		this.validStatus = validStatus;
	}

	@Column(name = "carBrands", length = 250)
	public String getCarBrands() {
		return this.carBrands;
	}

	public void setCarBrands(String carBrands) {
		this.carBrands = carBrands;
	}
}
