package ins.sino.claimcar.certify.vo;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!
import java.util.Date;


/**
 * Vo Base Class of PO PrpLCertifyCode
 */ 
public class PrpLCertifyCodeVoBase implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Long id;
	private String certifyTypeCode;
	private String certifyTypeName;
	private String upCertifyCode;
	private String upCertifyName;
	private String mustUpload;
	private String validStatus;
	private String flag;
	private String remark;
	private String createUser;
	private Date createTime;
	private String updateUser;
	private Date updateTime;

    protected PrpLCertifyCodeVoBase() {
	
    }

    
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getCertifyTypeCode() {
		return this.certifyTypeCode;
	}

	public void setCertifyTypeCode(String certifyTypeCode) {
		this.certifyTypeCode = certifyTypeCode;
	}

	public String getCertifyTypeName() {
		return this.certifyTypeName;
	}

	public void setCertifyTypeName(String certifyTypeName) {
		this.certifyTypeName = certifyTypeName;
	}

	public String getUpCertifyCode() {
		return this.upCertifyCode;
	}

	public void setUpCertifyCode(String upCertifyCode) {
		this.upCertifyCode = upCertifyCode;
	}

	public String getUpCertifyName() {
		return this.upCertifyName;
	}

	public void setUpCertifyName(String upCertifyName) {
		this.upCertifyName = upCertifyName;
	}

	public String getMustUpload() {
		return this.mustUpload;
	}

	public void setMustUpload(String mustUpload) {
		this.mustUpload = mustUpload;
	}

	public String getValidStatus() {
		return this.validStatus;
	}

	public void setValidStatus(String validStatus) {
		this.validStatus = validStatus;
	}

	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}
