package ins.sino.claimcar.manager.vo;

import java.util.Date;




// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!


/**
 * Vo Base Class of PO PrpLUserHolidayGrade
 */ 
public class PrpLUserHolidayGradeVoBase implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Long id;
	private Long gradeId;
	private String gradeName;
	private String transferCode;
	private String transferName;
	private Date createTime;
	private String createUser;
	private Date updateTime;
	private String updateUser;
	

    protected PrpLUserHolidayGradeVoBase() {
	
    }

    
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}


	public Long getGradeId  () {
		return this.gradeId  ;
	}

	public void setGradeId  (Long gradeId  ) {
		this.gradeId   = gradeId  ;
	}

	public String getGradeName() {
		return this.gradeName;
	}

	public void setGradeName(String gradeName) {
		this.gradeName = gradeName;
	}

	public String getTransferCode() {
		return this.transferCode;
	}

	public void setTransferCode(String transferCode) {
		this.transferCode = transferCode;
	}

	public String getTransferName() {
		return this.transferName;
	}

	public void setTransferName(String transferName) {
		this.transferName = transferName;
	}


	public Date getCreateTime() {
		return createTime;
	}


	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}


	public String getCreateUser() {
		return createUser;
	}


	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}


	public Date getUpdateTime() {
		return updateTime;
	}


	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}


	public String getUpdateUser() {
		return updateUser;
	}


	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}
}
