package ins.sino.claimcar.manager.vo;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!
import java.util.ArrayList;
import java.util.Date;
import java.util.List;


/**
 * Vo Base Class of PO PrpLUserHoliday
 */ 
public class PrpLUserHolidayVoBase implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Long id;
	private String userCode;
	private String userName;
	private String comCode;
	private String permission  ;
	private Date startDate;
	private Date endDate;
	private Date leaveDate;
	private String daysNum;
	private String cause;
	private String mobileNo;
	private String phone;
	private String checkerCode;
	private String checkerName;
	private String checkOption;
	private Date checkTime;
	private Date createTime;
	private String createUser;
	private Date updateTime;
	private String updateUser;
	private String status;
	private String checkStatus;
	private Date cancelTime;
	private List<PrpLUserHolidayGradeVo> prpLUserHolidayGrades = new ArrayList<PrpLUserHolidayGradeVo>(0);

    protected PrpLUserHolidayVoBase() {
	
    }

    
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getUserCode() {
		return this.userCode;
	}

	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getComCode() {
		return this.comCode;
	}

	public void setComCode(String comCode) {
		this.comCode = comCode;
	}

	public String getPermission  () {
		return this.permission  ;
	}

	public void setPermission  (String permission  ) {
		this.permission   = permission  ;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Date getLeaveDate() {
		return this.leaveDate;
	}

	public void setLeaveDate(Date leaveDate) {
		this.leaveDate = leaveDate;
	}

	public String getDaysNum() {
		return this.daysNum;
	}

	public void setDaysNum(String daysNum) {
		this.daysNum = daysNum;
	}

	public String getCause() {
		return this.cause;
	}

	public void setCause(String cause) {
		this.cause = cause;
	}

	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getCheckerCode() {
		return this.checkerCode;
	}

	public void setCheckerCode(String checkerCode) {
		this.checkerCode = checkerCode;
	}

	public String getCheckerName() {
		return this.checkerName;
	}

	public void setCheckerName(String checkerName) {
		this.checkerName = checkerName;
	}

	public String getCheckOption() {
		return this.checkOption;
	}

	public void setCheckOption(String cherkOption) {
		this.checkOption = cherkOption;
	}

	public Date getCheckTime() {
		return this.checkTime;
	}

	public void setCheckTime(Date checkTime) {
		this.checkTime = checkTime;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public List<PrpLUserHolidayGradeVo> getPrpLUserHolidayGrades() {
		return this.prpLUserHolidayGrades;
	}

	public void setPrpLUserHolidayGrades(List<PrpLUserHolidayGradeVo> prpLUserHolidayGrades) {
		this.prpLUserHolidayGrades = prpLUserHolidayGrades;
	}


	public String getStatus() {
		return status;
	}


	public void setStatus(String status) {
		this.status = status;
	}


	public String getCheckStatus() {
		return checkStatus;
	}


	public void setCheckStatus(String checkStatus) {
		this.checkStatus = checkStatus;
	}


	public Date getCancelTime() {
		return cancelTime;
	}


	public void setCancelTime(Date cancelTime) {
		this.cancelTime = cancelTime;
	}
}
