package ins.sino.claimcar.manager.vo;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!
import java.util.Date;


/**
 * Vo Base Class of PO SysAgentfactoryId
 */ 
public class PrplSysAgentfactoryVoBase implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private String agentCode;
	private String agentName;
	private String addressName;
	private String postCode;
	private String agentType;
	private String permitNo;
	private String linkerName;
	private Date bargainDate;
	private String phoneNumber;
	private String faxNumber;
	private String comCode;
	private String handlerCode;
	private String upperAgentCode;
	private String newAgentCode;
	private String validStatus;
	private String articleCode;
	private String flag;
	private String agenteName;
	private String permitFlag;
	private String prinCipalName;
	private String mobile;
	private String email;
	private String netAddress;
	private String bank;
	private String account;
	private String lowerViewFlag;
	private String agentShortName;
	private String createrCode;
	private String createTime;
	private String updaterCode;
	private String updateDate;
	private Date startDate;
	private Date endDate;
	private String saleSchannelCode;
	private String isAdd;
	private String checkRemark;
	private String sendMsgFlag;

	public String getAgentCode() {
		return this.agentCode;
	}

	public void setAgentCode(String agentCode) {
		this.agentCode = agentCode;
	}

	public String getAgentName() {
		return this.agentName;
	}

	public void setAgentName(String agentName) {
		this.agentName = agentName;
	}

	public String getAddressName() {
		return this.addressName;
	}

	public void setAddressName(String addressName) {
		this.addressName = addressName;
	}

	public String getPostCode() {
		return this.postCode;
	}

	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}

	public String getAgentType() {
		return this.agentType;
	}

	public void setAgentType(String agentType) {
		this.agentType = agentType;
	}

	public String getPermitNo() {
		return this.permitNo;
	}

	public void setPermitNo(String permitNo) {
		this.permitNo = permitNo;
	}

	public String getLinkerName() {
		return this.linkerName;
	}

	public void setLinkerName(String linkerName) {
		this.linkerName = linkerName;
	}

	public Date getBargainDate() {
		return this.bargainDate;
	}

	public void setBargainDate(Date bargainDate) {
		this.bargainDate = bargainDate;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getFaxNumber() {
		return this.faxNumber;
	}

	public void setFaxNumber(String faxNumber) {
		this.faxNumber = faxNumber;
	}

	public String getComCode() {
		return this.comCode;
	}

	public void setComCode(String comCode) {
		this.comCode = comCode;
	}

	public String getHandlerCode() {
		return this.handlerCode;
	}

	public void setHandlerCode(String handlerCode) {
		this.handlerCode = handlerCode;
	}

	public String getUpperAgentCode() {
		return this.upperAgentCode;
	}

	public void setUpperAgentCode(String upperAgentCode) {
		this.upperAgentCode = upperAgentCode;
	}

	public String getNewAgentCode() {
		return this.newAgentCode;
	}

	public void setNewAgentCode(String newAgentCode) {
		this.newAgentCode = newAgentCode;
	}

	public String getValidStatus() {
		return this.validStatus;
	}

	public void setValidStatus(String validStatus) {
		this.validStatus = validStatus;
	}

	public String getArticleCode() {
		return this.articleCode;
	}

	public void setArticleCode(String articleCode) {
		this.articleCode = articleCode;
	}

	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	public String getAgenteName() {
		return this.agenteName;
	}

	public void setAgenteName(String agenteName) {
		this.agenteName = agenteName;
	}

	public String getPermitFlag() {
		return this.permitFlag;
	}

	public void setPermitFlag(String permitFlag) {
		this.permitFlag = permitFlag;
	}

	public String getPrinCipalName() {
		return this.prinCipalName;
	}

	public void setPrinCipalName(String prinCipalName) {
		this.prinCipalName = prinCipalName;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getNetAddress() {
		return this.netAddress;
	}

	public void setNetAddress(String netAddress) {
		this.netAddress = netAddress;
	}

	public String getBank() {
		return this.bank;
	}

	public void setBank(String bank) {
		this.bank = bank;
	}

	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getLowerViewFlag() {
		return this.lowerViewFlag;
	}

	public void setLowerViewFlag(String lowerViewFlag) {
		this.lowerViewFlag = lowerViewFlag;
	}

	public String getAgentShortName() {
		return this.agentShortName;
	}

	public void setAgentShortName(String agentShortName) {
		this.agentShortName = agentShortName;
	}

	public String getCreaterCode() {
		return this.createrCode;
	}

	public void setCreaterCode(String createrCode) {
		this.createrCode = createrCode;
	}

	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	public String getUpdaterCode() {
		return this.updaterCode;
	}

	public void setUpdaterCode(String updaterCode) {
		this.updaterCode = updaterCode;
	}

	public String getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(String updateDate) {
		this.updateDate = updateDate;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getSaleSchannelCode() {
		return this.saleSchannelCode;
	}

	public void setSaleSchannelCode(String saleSchannelCode) {
		this.saleSchannelCode = saleSchannelCode;
	}

	public String getIsAdd() {
		return this.isAdd;
	}

	public void setIsAdd(String isAdd) {
		this.isAdd = isAdd;
	}

	public String getCheckRemark() {
		return this.checkRemark;
	}

	public void setCheckRemark(String checkRemark) {
		this.checkRemark = checkRemark;
	}

	public String getSendMsgFlag() {
		return this.sendMsgFlag;
	}

	public void setSendMsgFlag(String sendMsgFlag) {
		this.sendMsgFlag = sendMsgFlag;
	}

}
