package ins.sino.claimcar.check.vo;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!
import java.util.Date;

/**
 * Vo Base Class of PO PrpLDisaster
 */
public class PrpLDisasterVoBase implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long id;
	private String registNo;
	private String policyNo;
	private String claimNo;
	private String disasterCodeOne;
	private String disasterNameOne;
	private String disasterTypeCode;
	private String disasterTypeName;
	private String disasterArea;
	private Date startTime;
	private Date endTime;
	private String flag;
	private String validFlag;
	private String remark;
	private String createUser;
	private Date createTime;
	private String updateUser;
	private Date updateTime;
	private String disasterCodeTwo;
	private String disasterNameTwo;

	protected PrpLDisasterVoBase(){

	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getRegistNo() {
		return this.registNo;
	}

	public void setRegistNo(String registNo) {
		this.registNo = registNo;
	}

	public String getPolicyNo() {
		return this.policyNo;
	}

	public void setPolicyNo(String policyNo) {
		this.policyNo = policyNo;
	}

	public String getClaimNo() {
		return this.claimNo;
	}

	public void setClaimNo(String claimNo) {
		this.claimNo = claimNo;
	}

	public String getDisasterCodeOne() {
		return this.disasterCodeOne;
	}

	public void setDisasterCodeOne(String disasterCodeOne) {
		this.disasterCodeOne = disasterCodeOne;
	}

	public String getDisasterNameOne() {
		return this.disasterNameOne;
	}

	public void setDisasterNameOne(String disasterNameOne) {
		this.disasterNameOne = disasterNameOne;
	}

	public String getDisasterTypeCode() {
		return this.disasterTypeCode;
	}

	public void setDisasterTypeCode(String disasterTypeCode) {
		this.disasterTypeCode = disasterTypeCode;
	}

	public String getDisasterTypeName() {
		return this.disasterTypeName;
	}

	public void setDisasterTypeName(String disasterTypeName) {
		this.disasterTypeName = disasterTypeName;
	}

	public String getDisasterArea() {
		return this.disasterArea;
	}

	public void setDisasterArea(String disasterArea) {
		this.disasterArea = disasterArea;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	public String getValidFlag() {
		return this.validFlag;
	}

	public void setValidFlag(String validFlag) {
		this.validFlag = validFlag;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getDisasterCodeTwo() {
		return this.disasterCodeTwo;
	}

	public void setDisasterCodeTwo(String disasterCodeTwo) {
		this.disasterCodeTwo = disasterCodeTwo;
	}

	public String getDisasterNameTwo() {
		return this.disasterNameTwo;
	}

	public void setDisasterNameTwo(String disasterNameTwo) {
		this.disasterNameTwo = disasterNameTwo;
	}
}
