package ins.sino.claimcar.check.vo;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!
import java.math.BigDecimal;
import java.util.Date;

/**
 * Vo Base Class of PO PrpLCheckProp
 */
public class PrpLCheckPropVoBase implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long id;
	private Long checkTaskId;
	private Long scheduleitem;
	private String registNo;
	private Long lossPartyId;
	private String lossPartyName;
	private String lossItemName;
	private String lossNum;
	private String lossDegreeCode;
	private String lossFeeType;
	private BigDecimal lossFee;
	private String validFlag;
	private String remark;
	private String flag;
	private String createUser;
	private Date createTime;
	private String updateUser;
	private Date updateTime;
	private String isNoClaim;

	protected PrpLCheckPropVoBase(){

	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getRegistNo() {
		return this.registNo;
	}

	public void setRegistNo(String registNo) {
		this.registNo = registNo;
	}

	public Long getLossPartyId() {
		return this.lossPartyId;
	}

	public void setLossPartyId(Long lossPartyId) {
		this.lossPartyId = lossPartyId;
	}

	public String getLossPartyName() {
		return this.lossPartyName;
	}

	public void setLossPartyName(String lossPartyName) {
		this.lossPartyName = lossPartyName;
	}

	public String getLossItemName() {
		return this.lossItemName;
	}

	public void setLossItemName(String lossItemName) {
		this.lossItemName = lossItemName;
	}

	public String getLossNum() {
		return this.lossNum;
	}

	public void setLossNum(String lossNum) {
		this.lossNum = lossNum;
	}

	public String getLossDegreeCode() {
		return this.lossDegreeCode;
	}

	public void setLossDegreeCode(String lossDegreeCode) {
		this.lossDegreeCode = lossDegreeCode;
	}

	public String getLossFeeType() {
		return this.lossFeeType;
	}

	public void setLossFeeType(String lossFeeType) {
		this.lossFeeType = lossFeeType;
	}

	public BigDecimal getLossFee() {
		return this.lossFee;
	}

	public void setLossFee(BigDecimal lossFee) {
		this.lossFee = lossFee;
	}

	public String getValidFlag() {
		return this.validFlag;
	}

	public void setValidFlag(String validFlag) {
		this.validFlag = validFlag;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Long getCheckTaskId() {
		return checkTaskId;
	}

	public void setCheckTaskId(Long checkTaskId) {
		this.checkTaskId = checkTaskId;
	}

	public Long getScheduleitem() {
		return scheduleitem;
	}

	public void setScheduleitem(Long scheduleitem) {
		this.scheduleitem = scheduleitem;
	}

	public String getIsNoClaim() {
		return this.isNoClaim;
	}
	
	public void setIsNoClaim(String isNoClaim) {
		this.isNoClaim = isNoClaim;
	}

}
