package ins.sino.claimcar.check.vo;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!
import java.util.Date;

/**
 * Vo Base Class of PO PrpLCheck
 */
public class PrpLCheckVoBase implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long id;
	private String registNo;
	private String singleAccidentFlag;
	private String damageTypeCode;
	private String manageType;
	private String damageCode;
	private String damOtherCode;
	private String waterLoggingLevel;
	private String claimType;
	private String mercyFlag;
	private String lossType;
	private String checkType;
	private String checkClass;
	private String isClaimSelf;
	private String isPropLoss;
	private String isPersonLoss;
	private String isSubRogation;
	private String reconcileFlag;
	private String majorCaseFlag;
	private Date chkSubmitTime;
	private Date reChkSubmitTime;
	private String validFlag;
	private String falg;
	private String remark;
	private String createUser;
	private Date createTime;
	private String updateUser;
	private Date updateTime;
	private String photoStatus;	//快赔照片审核不通过：11-对方定损照片,12-已方定损照片';
	private PrpLCheckTaskVo prpLCheckTask;
	private String noDutyFlag;	//是否免责情形
	private String noDutyReason;	//免责原因
	private String persHandleType;	//人伤案件处理类型
	private String operateStatus;	//查勘提交状态
	private String checkCode;//查勘费机构

	protected PrpLCheckVoBase(){

	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	

	public String getRegistNo() {
		return this.registNo;
	}

	public void setRegistNo(String registNo) {
		this.registNo = registNo;
	}

	public String getSingleAccidentFlag() {
		return this.singleAccidentFlag;
	}

	public void setSingleAccidentFlag(String singleAccidentFlag) {
		this.singleAccidentFlag = singleAccidentFlag;
	}

	public String getDamageTypeCode() {
		return this.damageTypeCode;
	}

	public void setDamageTypeCode(String damageTypeCode) {
		this.damageTypeCode = damageTypeCode;
	}

	public String getManageType() {
		return this.manageType;
	}

	public void setManageType(String manageType) {
		this.manageType = manageType;
	}

	public String getDamageCode() {
		return this.damageCode;
	}

	public void setDamageCode(String damageCode) {
		this.damageCode = damageCode;
	}

	public String getClaimType() {
		return this.claimType;
	}

	public void setClaimType(String claimType) {
		this.claimType = claimType;
	}

	public String getMercyFlag() {
		return this.mercyFlag;
	}

	public void setMercyFlag(String mercyFlag) {
		this.mercyFlag = mercyFlag;
	}

	public String getLossType() {
		return this.lossType;
	}

	public void setLossType(String lossType) {
		this.lossType = lossType;
	}

	public String getCheckType() {
		return this.checkType;
	}

	public void setCheckType(String checkType) {
		this.checkType = checkType;
	}

	public String getCheckClass() {
		return this.checkClass;
	}

	public void setCheckClass(String checkClass) {
		this.checkClass = checkClass;
	}

	public String getIsClaimSelf() {
		return this.isClaimSelf;
	}

	public void setIsClaimSelf(String isClaimSelf) {
		this.isClaimSelf = isClaimSelf;
	}

	public String getIsPropLoss() {
		return this.isPropLoss;
	}

	public void setIsPropLoss(String isPropLoss) {
		this.isPropLoss = isPropLoss;
	}

	public String getIsPersonLoss() {
		return this.isPersonLoss;
	}

	public void setIsPersonLoss(String isPersonLoss) {
		this.isPersonLoss = isPersonLoss;
	}

	public String getIsSubRogation() {
		return this.isSubRogation;
	}

	public void setIsSubRogation(String isSubRogation) {
		this.isSubRogation = isSubRogation;
	}

	public String getReconcileFlag() {
		return this.reconcileFlag;
	}

	public void setReconcileFlag(String reconcileFlag) {
		this.reconcileFlag = reconcileFlag;
	}

	public String getMajorCaseFlag() {
		return this.majorCaseFlag;
	}

	public void setMajorCaseFlag(String majorCaseFlag) {
		this.majorCaseFlag = majorCaseFlag;
	}

	public Date getChkSubmitTime() {
		return this.chkSubmitTime;
	}

	public void setChkSubmitTime(Date chkSubmitTime) {
		this.chkSubmitTime = chkSubmitTime;
	}

	public Date getReChkSubmitTime() {
		return this.reChkSubmitTime;
	}

	public void setReChkSubmitTime(Date reChkSubmitTime) {
		this.reChkSubmitTime = reChkSubmitTime;
	}

	public String getValidFlag() {
		return this.validFlag;
	}

	public void setValidFlag(String validFlag) {
		this.validFlag = validFlag;
	}

	public String getFalg() {
		return this.falg;
	}

	public void setFalg(String falg) {
		this.falg = falg;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public PrpLCheckTaskVo getPrpLCheckTask() {
		return this.prpLCheckTask;
	}

	public void setPrpLCheckTask(PrpLCheckTaskVo prpLCheckTask) {
		this.prpLCheckTask = prpLCheckTask;
	}

	public String getDamOtherCode() {
		return this.damOtherCode;
	}

	public void setDamOtherCode(String damOtherCode) {
		this.damOtherCode = damOtherCode;
	}

	public String getWaterLoggingLevel() {
		return this.waterLoggingLevel;
	}

	public void setWaterLoggingLevel(String waterLoggingLevel) {
		this.waterLoggingLevel = waterLoggingLevel;
	}

	public String getPhotoStatus() {
		return photoStatus;
	}

	public void setPhotoStatus(String photoStatus) {
		this.photoStatus = photoStatus;
	}

	public String getNoDutyFlag() {
		return noDutyFlag;
	}

	public void setNoDutyFlag(String noDutyFlag) {
		this.noDutyFlag = noDutyFlag;
	}

	public String getNoDutyReason() {
		return noDutyReason;
	}

	public void setNoDutyReason(String noDutyReason) {
		this.noDutyReason = noDutyReason;
	}

	public String getPersHandleType() {
		return persHandleType;
	}

	public void setPersHandleType(String persHandleType) {
		this.persHandleType = persHandleType;
	}

	public String getOperateStatus() {
		return operateStatus;
	}

	public void setOperateStatus(String operateStatus) {
		this.operateStatus = operateStatus;
	}

	public String getCheckCode() {
		return checkCode;
	}

	public void setCheckCode(String checkCode) {
		this.checkCode = checkCode;
	}
	
}
