package ins.sino.claimcar.claim.po;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.constraints.NotBlank;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * POJO Class PrpDAccidentDeduct
 */
@Entity
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@TableGenerator(name = "utiSequence", table = "UTISEQUENCE", pkColumnName = "GenName", valueColumnName = "GenValue", pkColumnValue = "PRPDACCIDENTDEDUCT_PK", allocationSize = 10)
@Table(name = "PRPDACCIDENTDEDUCT")
public class PrpDAccidentDeduct implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Long id;
	private String riskCode;
	private String kindCode;
	private String indemnityDuty;
	private String dangerLevel;
	private BigDecimal deductibleRate;
	private String validStatus;
	private Date validDate;
	private String deductPeriod;
	private String clauseType;

	@Id
	@NotBlank
	@Column(name = "ID", unique = true, nullable = false, precision=12, scale=0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "RISKCODE", nullable = false, length=4)
	public String getRiskCode() {
		return this.riskCode;
	}

	public void setRiskCode(String riskCode) {
		this.riskCode = riskCode;
	}

	@Column(name = "KINDCODE", nullable = false, length=7)
	public String getKindCode() {
		return this.kindCode;
	}

	public void setKindCode(String kindCode) {
		this.kindCode = kindCode;
	}

	@Column(name = "INDEMNITYDUTY", nullable = false, length=2)
	public String getIndemnityDuty() {
		return this.indemnityDuty;
	}

	public void setIndemnityDuty(String indemnityDuty) {
		this.indemnityDuty = indemnityDuty;
	}

	@Column(name = "DANGERLEVEL", nullable = false, length=7)
	public String getDangerLevel() {
		return this.dangerLevel;
	}

	public void setDangerLevel(String dangerLevel) {
		this.dangerLevel = dangerLevel;
	}

	@Column(name = "DEDUCTIBLERATE", precision=8, scale=4)
	public BigDecimal getDeductibleRate() {
		return this.deductibleRate;
	}

	public void setDeductibleRate(BigDecimal deductibleRate) {
		this.deductibleRate = deductibleRate;
	}

	@Column(name = "VALIDSTATUS", length=1)
	public String getValidStatus() {
		return this.validStatus;
	}

	public void setValidStatus(String validStatus) {
		this.validStatus = validStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VALIDDATE", length=7)
	public Date getValidDate() {
		return this.validDate;
	}

	public void setValidDate(Date validDate) {
		this.validDate = validDate;
	}

	@Column(name = "DEDUCTPERIOD", nullable = false, length=5)
	public String getDeductPeriod() {
		return this.deductPeriod;
	}

	public void setDeductPeriod(String deductPeriod) {
		this.deductPeriod = deductPeriod;
	}

	@Column(name = "CLAUSETYPE", nullable = false, length=3)
	public String getClauseType() {
		return this.clauseType;
	}

	public void setClauseType(String clauseType) {
		this.clauseType = clauseType;
	}
}
