package ins.sino.claimcar.manager.po;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * POJO Class AccBankName 行号查询表po
 */
@Entity
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "ACCBANKNAME")
public class AccBankName implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private String bankCode;
	private String bankName;
	private String address;
	private String bankLevel;
	private String belongBank;
	private String provincial;
	private String city;
	private String F01;
	private String F02;
	private String F03;
	private String validStatus;
	private String flag;
	private String remark;


	@Id
	@Column(name = "BANKCODE", unique = true, nullable = false, scale=0)
	public String getBankCode() {
		return this.bankCode;
	}

	public void setBankCode(String bankCode) {
		this.bankCode = bankCode;
	}

	@Column(name = "ADDRESS", length=150)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "BANKLEVEL", length=30)
	public String getBankLevel() {
		return this.bankLevel;
	}

	public void setBankLevel(String bankLevel) {
		this.bankLevel = bankLevel;
	}

	@Column(name = "BELONGBANK", length = 50)
	public String getBelongBank() {
		return this.belongBank;
	}

	public void setBelongBank(String belongBank) {
		this.belongBank = belongBank;
	}

	@Column(name = "PROVINCIAL", length=50)
	public String getProvincial() {
		return this.provincial;
	}

	public void setProvincial(String provincial) {
		this.provincial = provincial;
	}

	@Column(name = "F01", length=30)
	public String getF01() {
		return this.F01;
	}

	public void setF01(String F01) {
		this.F01 = F01;
	}
	
	@Column(name = "F02", length=30)
	public String getF02() {
		return this.F02;
	}

	public void setF02(String F02) {
		this.F02 = F02;
	}
	
	@Column(name = "F03", length=30)
	public String getF03() {
		return this.F03;
	}

	public void setF03(String F03) {
		this.F03 = F03;
	}

	@Column(name = "VALIDSTATUS", length = 1)
	public String getValidStatus() {
		return this.validStatus;
	}

	public void setValidStatus(String validStatus) {
		this.validStatus = validStatus;
	}


	@Column(name = "BANKNAME", length=150)
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}


	@Column(name = "CITY", length=50)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}


	@Column(name = "FLAG", length=10)
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	@Column(name = "REMARK",length=150)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
