package ins.sino.claimcar.manager.po;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * POJO Class PrpLRepairBrand
 */
@Entity
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@TableGenerator(name = "utiSequence", table = "UTISEQUENCE", pkColumnName = "GenName", valueColumnName = "GenValue", pkColumnValue = "PRPLREPAIRBRAND_PK", allocationSize = 10)
@Table(name = "PRPLREPAIRBRAND")
public class PrpLRepairBrand implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long id;
	private PrpLRepairFactory prpLRepairFactory;
	private String brandName;
	private String brandCode;
	private BigDecimal compRate;
	private BigDecimal hourRate;
	private String remark;

	@Id
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "utiSequence")
	@Column(name = "ID", unique = true, nullable = false, precision = 12, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REPAIRID", nullable = false)
	public PrpLRepairFactory getPrpLRepairFactory() {
		return this.prpLRepairFactory;
	}

	public void setPrpLRepairFactory(PrpLRepairFactory prpLRepairFactory) {
		this.prpLRepairFactory = prpLRepairFactory;
	}

	@Column(name = "BRANDNAME", length = 20)
	public String getBrandName() {
		return this.brandName;
	}

	public void setBrandName(String brandName) {
		this.brandName = brandName;
	}

	@Column(name = "BRANDCODE", length = 40)
	public String getBrandCode() {
		return this.brandCode;
	}

	public void setBrandCode(String brandCode) {
		this.brandCode = brandCode;
	}

	@Column(name = "COMPRATE", precision = 8, scale = 4)
	public BigDecimal getCompRate() {
		return this.compRate;
	}

	public void setCompRate(BigDecimal compRate) {
		this.compRate = compRate;
	}

	@Column(name = "HOURRATE", precision = 8, scale = 4)
	public BigDecimal getHourRate() {
		return this.hourRate;
	}

	public void setHourRate(BigDecimal hourRate) {
		this.hourRate = hourRate;
	}

	@Column(name = "REMARK")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}
}
