package ins.sino.claimcar.check.po;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!
import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * POJO Class PrpLCheckCar
 */
@Entity
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@TableGenerator(name = "utiSequence", table = "UTISEQUENCE", pkColumnName = "GenName", valueColumnName = "GenValue", pkColumnValue = "PRPLCHECKCAR_PK", allocationSize = 10)
@Table(name = "PRPLCHECKCAR")
public class PrpLCheckCar implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Long carid;
	private PrpLCheckTask prpLCheckTask;
	private String registNo;
	private Integer serialNo;
	private Long scheduleitem; 
	private String lossFlag;
	private String checkAdress;
	private Date checkTime;
	private BigDecimal lossFee;
	private BigDecimal rescueFee;
	private String lossPart;
	private String ciIndemDuty;
	private String indemnityDuty;
	private BigDecimal indemnityDutyRate;
	private String kindCode;
	private String validFlag;
	private String remark;
	private String flag;
	private String createUser;
	private Date createTime;
	private String updateUser;
	private Date updateTime;
	private PrpLCheckCarInfo  prpLCheckCarInfo ;
	private PrpLCheckDriver prpLCheckDriver;

	@Id
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "utiSequence")
	@Column(name = "CARID", unique = true, nullable = false, precision=13, scale=0)
	public Long getCarid() {
		return this.carid;
	}

	public void setCarid(Long carid) {
		this.carid = carid;
	}

	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CHECKTASKID", nullable = false)
	public PrpLCheckTask getPrpLCheckTask() {
		return this.prpLCheckTask;
	}

	public void setPrpLCheckTask(PrpLCheckTask prpLCheckTask) {
		this.prpLCheckTask = prpLCheckTask;
	}

	@Column(name = "REGISTNO", nullable = false, length=30)
	public String getRegistNo() {
		return this.registNo;
	}

	public void setRegistNo(String registNo) {
		this.registNo = registNo;
	}

	@Column(name = "SERIALNO", nullable = false, precision=5, scale=0)
	public Integer getSerialNo() {
		return this.serialNo;
	}

	public void setSerialNo(Integer serialNo) {
		this.serialNo = serialNo;
	}
	
	@Column(name = "LOSSFLAG", nullable = false, length=2)
	public String getLossFlag() {
		return this.lossFlag;
	}

	public void setLossFlag(String lossFlag) {
		this.lossFlag = lossFlag;
	}

	@Column(name = "CHECKADRESS", length=200)
	public String getCheckAdress() {
		return this.checkAdress;
	}

	public void setCheckAdress(String checkAdress) {
		this.checkAdress = checkAdress;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CHECKTIME", length=7)
	public Date getCheckTime() {
		return this.checkTime;
	}

	public void setCheckTime(Date checkTime) {
		this.checkTime = checkTime;
	}

	@Column(name = "LOSSFEE", precision=14)
	public BigDecimal getLossFee() {
		return this.lossFee;
	}

	public void setLossFee(BigDecimal lossFee) {
		this.lossFee = lossFee;
	}

	@Column(name = "RESCUEFEE", precision=14)
	public BigDecimal getRescueFee() {
		return this.rescueFee;
	}

	@Column(name = "SCHEDULEITEM", precision=19)
	public Long getScheduleitem() {
		return scheduleitem;
	}

	public void setScheduleitem(Long scheduleitem) {
		this.scheduleitem = scheduleitem;
	}

	public void setRescueFee(BigDecimal rescueFee) {
		this.rescueFee = rescueFee;
	}

	@Column(name = "LOSSPART", length=120)
	public String getLossPart() {
		return this.lossPart;
	}

	public void setLossPart(String lossPart) {
		this.lossPart = lossPart;
	}

	@Column(name = "CIINDEMDUTY", length=2)
	public String getCiIndemDuty() {
		return this.ciIndemDuty;
	}

	public void setCiIndemDuty(String ciIndemDuty) {
		this.ciIndemDuty = ciIndemDuty;
	}

	@Column(name = "INDEMNITYDUTY", length=1)
	public String getIndemnityDuty() {
		return this.indemnityDuty;
	}

	public void setIndemnityDuty(String indemnityDuty) {
		this.indemnityDuty = indemnityDuty;
	}

	@Column(name = "INDEMNITYDUTYRATE", precision=8, scale=4)
	public BigDecimal getIndemnityDutyRate() {
		return this.indemnityDutyRate;
	}

	public void setIndemnityDutyRate(BigDecimal indemnityDutyRate) {
		this.indemnityDutyRate = indemnityDutyRate;
	}

	@Column(name = "KINDCODE", length=10)
	public String getKindCode() {
		return this.kindCode;
	}

	public void setKindCode(String kindCode) {
		this.kindCode = kindCode;
	}

	@Column(name = "VALIDFLAG", length=2)
	public String getValidFlag() {
		return this.validFlag;
	}

	public void setValidFlag(String validFlag) {
		this.validFlag = validFlag;
	}

	@Column(name = "REMARK")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "FLAG", length=10)
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	@Column(name = "CREATEUSER", nullable = false, length=10)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATETIME", nullable = false, length=7)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "UPDATEUSER", nullable = false, length=10)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATETIME", nullable = false, length=7)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@OneToOne(cascade = CascadeType.ALL,fetch=FetchType.LAZY, mappedBy="prpLCheckCar")
	public PrpLCheckCarInfo  getPrpLCheckCarInfo () {
		return this.prpLCheckCarInfo ;
	}

	public void setPrpLCheckCarInfo (PrpLCheckCarInfo  prpLCheckCarInfo ) {
		this.prpLCheckCarInfo  = prpLCheckCarInfo ;
	}

	@OneToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "prpLCheckCar")
	public PrpLCheckDriver getPrpLCheckDriver() {
		return this.prpLCheckDriver;
	}

	public void setPrpLCheckDriver(PrpLCheckDriver prpLCheckDriver) {
		this.prpLCheckDriver = prpLCheckDriver;
	}
}
