package ins.sino.claimcar.check.po;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * POJO Class PrpLCheckExt
 */
@Entity
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@TableGenerator(name = "utiSequence", table = "UTISEQUENCE", pkColumnName = "GenName", valueColumnName = "GenValue", pkColumnValue = "PRPLCHECKEXT_PK", allocationSize = 10)
@Table(name = "PRPLCHECKEXT")
public class PrpLCheckExt implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Long id;
	private PrpLCheckTask prpLCheckTask;
	private String registNo;
	private String claimNo;
	private String checkExtCode;
	private String columnValue;
	private String checkExtName;
	private String validFlag;
	private String remark;
	private String flag;

	@Id
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "utiSequence")
	@Column(name = "ID", unique = true, nullable = false, scale=0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CHECKID", nullable = false)
	public PrpLCheckTask getPrpLCheckTask() {
		return this.prpLCheckTask;
	}

	public void setPrpLCheckTask(PrpLCheckTask prpLCheckTask) {
		this.prpLCheckTask = prpLCheckTask;
	}

	@Column(name = "REGISTNO", length=30)
	public String getRegistNo() {
		return this.registNo;
	}

	public void setRegistNo(String registNo) {
		this.registNo = registNo;
	}

	@Column(name = "CLAIMNO", length=22)
	public String getClaimNo() {
		return this.claimNo;
	}

	public void setClaimNo(String claimNo) {
		this.claimNo = claimNo;
	}

	@Column(name = "CHECKEXTCODE", length=20)
	public String getCheckExtCode() {
		return this.checkExtCode;
	}

	public void setCheckExtCode(String checkExtCode) {
		this.checkExtCode = checkExtCode;
	}

	@Column(name = "COLUMNVALUE", length=40)
	public String getColumnValue() {
		return this.columnValue;
	}

	public void setColumnValue(String columnValue) {
		this.columnValue = columnValue;
	}

	@Column(name = "CHECKEXTNAME", length=200)
	public String getCheckExtName() {
		return this.checkExtName;
	}

	public void setCheckExtName(String checkExtName) {
		this.checkExtName = checkExtName;
	}

	@Column(name = "VALIDFLAG", length=1)
	public String getValidFlag() {
		return this.validFlag;
	}

	public void setValidFlag(String validFlag) {
		this.validFlag = validFlag;
	}

	@Column(name = "REMARK")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "FLAG", length=10)
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}
}
