package ins.sino.claimcar.regist.po;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * POJO Class PrpCMain
 */
@Entity
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "PRPCMAIN")
public class PrpCMain implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private String policyNo;
	private String classCode;
	private String riskCode;
	private String proposalNo;
	private String contractNo;
	private String policySort;
	private String printNo;
	private String businessNature;
	private String language;
	private String policyType;
	private String appliCode;
	private String appliName;
	private String appliAddress;
	private String insuredCode;
	private String insuredName;
	private String insuredAddress;
	private Date operateDate;
	private Date startDate;
	private Long startHour;
	private Date endDate;
	private Long endHour;
	private BigDecimal pureRate;
	private BigDecimal disRate;
	private BigDecimal discount;
	private String currency;
	private BigDecimal sumValue;
	private BigDecimal sumAmount;
	private BigDecimal sumDiscount;
	private BigDecimal sumPremium;
	private BigDecimal sumSubprem;
	private Long sumQuantity;
	private String judicalCode;
	private String judicalScope;
	private String autoTransRenewFlag;
	private String argueSolution;
	private String arbitBoardName;
	private Long payTimes;
	private Long endorseTimes;
	private Long claimTimes;
	private String makeCom;
	private String operateSite;
	private String comCode;
	private String handlerCode;
	private String handler1Code;
	private String approverCode;
	private String underWriteCode;
	private String underWriteName;
	private String operatorCode;
	private Date inputDate;
	private Long inputHour;
	private Date underWriteEndDate;
	private Date statisticsYm;
	private String agentCode;
	private String coinsFlag;
	private String reinsFlag;
	private String allinsFlag;
	private String underWriteFlag;
	private String othFlag;
	private String flag;
	private BigDecimal disrate1;
	private String businessFlag;
	private String updaterCode;
	private Date updateDate;
	private String updateHour;
	private Date signDate;
	private String shareHolderFlag;
	private String agreementNo;
	private String inquiryNo;
	private String payMode;
	private String remark;
	private String visaCode;
	private String manualType;
	private Integer startMinute;
	private Integer endMinute;
	private String nationFlag;
	private String jfeeFlag;
	private Date precheckDate;
	private String handlerName;
	private String handler1Name;
	private String payrefCode;
	private String payrefName;
	private Date payrefTime;
	private Date printTime;
	private Byte printTimes;
	private String coinsComCode;
	private String businessClass;
	private Date updateTime;
	private Date inputTime;
	private Date underWriteEndTime;
	private String farmFlag;
	private String otherBusinessFlag;
	private String foreignFlag;
	private String stockholderCode;
	private String stockholderName;
	private String stopTimes;
	private Date newStartDate;
	private Date newendDate;
	private String businessPlate;
	private String merchantcode;
	private String merchantname;
	private String merchantsubcode;
	private String merchantsubname;
	private String vipflag;
	private BigDecimal additionalcostrate;
	private BigDecimal shortRate;
	private String businesssubclass;
	private String defined1;
	private BigDecimal sumreservepremium;
	private String businessdemandno;
	private String reservedemandno;
	private String autopricedemandno;
	private String manualflag;
	private String groupno1;
	private String groupno2;
	private String serviceMobile;
	private List<PrpCInsured> prpCInsureds = new ArrayList<PrpCInsured>(0);
	private List<PrpCItemKind> prpCItemKinds = new ArrayList<PrpCItemKind>(0);
	private List<PrpCItemCar> prpCItemCars = new ArrayList<PrpCItemCar>(0);
	private List<PrpCengage> prpCengages = new ArrayList<PrpCengage>(0);
	@Id
	@Column(name = "POLICYNO", unique = true, nullable = false, length=22)
	public String getPolicyNo() {
		return this.policyNo;
	}

	public void setPolicyNo(String policyNo) {
		this.policyNo = policyNo;
	}

	@Column(name = "CLASSCODE", nullable = false, length=3)
	public String getClassCode() {
		return this.classCode;
	}

	public void setClassCode(String classCode) {
		this.classCode = classCode;
	}

	@Column(name = "RISKCODE", nullable = false, length=4)
	public String getRiskCode() {
		return this.riskCode;
	}

	public void setRiskCode(String riskCode) {
		this.riskCode = riskCode;
	}

	@Column(name = "PROPOSALNO", length=22)
	public String getProposalNo() {
		return this.proposalNo;
	}

	public void setProposalNo(String proposalNo) {
		this.proposalNo = proposalNo;
	}

	@Column(name = "CONTRACTNO", length=22)
	public String getContractNo() {
		return this.contractNo;
	}

	public void setContractNo(String contractNo) {
		this.contractNo = contractNo;
	}

	@Column(name = "POLICYSORT", nullable = false, length=1)
	public String getPolicySort() {
		return this.policySort;
	}

	public void setPolicySort(String policySort) {
		this.policySort = policySort;
	}

	@Column(name = "PRINTNO", length=22)
	public String getPrintNo() {
		return this.printNo;
	}

	public void setPrintNo(String printNo) {
		this.printNo = printNo;
	}

	@Column(name = "BUSINESSNATURE", nullable = false, length=1)
	public String getBusinessNature() {
		return this.businessNature;
	}

	public void setBusinessNature(String businessNature) {
		this.businessNature = businessNature;
	}

	@Column(name = "LANGUAGE", length=1)
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	@Column(name = "POLICYTYPE", length=2)
	public String getPolicyType() {
		return this.policyType;
	}

	public void setPolicyType(String policyType) {
		this.policyType = policyType;
	}

	@Column(name = "APPLICODE", length=20)
	public String getAppliCode() {
		return this.appliCode;
	}

	public void setAppliCode(String appliCode) {
		this.appliCode = appliCode;
	}

	@Column(name = "APPLINAME", length=120)
	public String getAppliName() {
		return this.appliName;
	}

	public void setAppliName(String appliName) {
		this.appliName = appliName;
	}

	@Column(name = "APPLIADDRESS")
	public String getAppliAddress() {
		return this.appliAddress;
	}

	public void setAppliAddress(String appliAddress) {
		this.appliAddress = appliAddress;
	}

	@Column(name = "INSUREDCODE", length=20)
	public String getInsuredCode() {
		return this.insuredCode;
	}

	public void setInsuredCode(String insuredCode) {
		this.insuredCode = insuredCode;
	}

	@Column(name = "INSUREDNAME", length=120)
	public String getInsuredName() {
		return this.insuredName;
	}

	public void setInsuredName(String insuredName) {
		this.insuredName = insuredName;
	}

	@Column(name = "INSUREDADDRESS")
	public String getInsuredAddress() {
		return this.insuredAddress;
	}

	public void setInsuredAddress(String insuredAddress) {
		this.insuredAddress = insuredAddress;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OPERATEDATE", length=7)
	public Date getOperateDate() {
		return this.operateDate;
	}

	public void setOperateDate(Date operateDate) {
		this.operateDate = operateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "STARTDATE", length=7)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Column(name = "STARTHOUR", precision=15, scale=0)
	public Long getStartHour() {
		return this.startHour;
	}

	public void setStartHour(Long startHour) {
		this.startHour = startHour;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ENDDATE", length=7)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "ENDHOUR", precision=15, scale=0)
	public Long getEndHour() {
		return this.endHour;
	}

	public void setEndHour(Long endHour) {
		this.endHour = endHour;
	}

	@Column(name = "PURERATE", precision=8, scale=4)
	public BigDecimal getPureRate() {
		return this.pureRate;
	}

	public void setPureRate(BigDecimal pureRate) {
		this.pureRate = pureRate;
	}

	@Column(name = "DISRATE", precision=8, scale=4)
	public BigDecimal getDisRate() {
		return this.disRate;
	}

	public void setDisRate(BigDecimal disRate) {
		this.disRate = disRate;
	}

	@Column(name = "DISCOUNT", precision=8, scale=4)
	public BigDecimal getDiscount() {
		return this.discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

	@Column(name = "CURRENCY", length=3)
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	@Column(name = "SUMVALUE", precision=14)
	public BigDecimal getSumValue() {
		return this.sumValue;
	}

	public void setSumValue(BigDecimal sumValue) {
		this.sumValue = sumValue;
	}

	@Column(name = "SUMAMOUNT", precision=14)
	public BigDecimal getSumAmount() {
		return this.sumAmount;
	}

	public void setSumAmount(BigDecimal sumAmount) {
		this.sumAmount = sumAmount;
	}

	@Column(name = "SUMDISCOUNT", precision=14)
	public BigDecimal getSumDiscount() {
		return this.sumDiscount;
	}

	public void setSumDiscount(BigDecimal sumDiscount) {
		this.sumDiscount = sumDiscount;
	}

	@Column(name = "SUMPREMIUM", precision=14)
	public BigDecimal getSumPremium() {
		return this.sumPremium;
	}

	public void setSumPremium(BigDecimal sumPremium) {
		this.sumPremium = sumPremium;
	}

	@Column(name = "SUMSUBPREM", precision=14)
	public BigDecimal getSumSubprem() {
		return this.sumSubprem;
	}

	public void setSumSubprem(BigDecimal sumSubprem) {
		this.sumSubprem = sumSubprem;
	}

	@Column(name = "SUMQUANTITY", precision=15, scale=0)
	public Long getSumQuantity() {
		return this.sumQuantity;
	}

	public void setSumQuantity(Long sumQuantity) {
		this.sumQuantity = sumQuantity;
	}

	@Column(name = "JUDICALCODE", length=1)
	public String getJudicalCode() {
		return this.judicalCode;
	}

	public void setJudicalCode(String judicalCode) {
		this.judicalCode = judicalCode;
	}

	@Column(name = "JUDICALSCOPE", length=40)
	public String getJudicalScope() {
		return this.judicalScope;
	}

	public void setJudicalScope(String judicalScope) {
		this.judicalScope = judicalScope;
	}

	@Column(name = "AUTOTRANSRENEWFLAG", length=1)
	public String getAutoTransRenewFlag() {
		return this.autoTransRenewFlag;
	}

	public void setAutoTransRenewFlag(String autoTransRenewFlag) {
		this.autoTransRenewFlag = autoTransRenewFlag;
	}

	@Column(name = "ARGUESOLUTION", length=1)
	public String getArgueSolution() {
		return this.argueSolution;
	}

	public void setArgueSolution(String argueSolution) {
		this.argueSolution = argueSolution;
	}

	@Column(name = "ARBITBOARDNAME", length=60)
	public String getArbitBoardName() {
		return this.arbitBoardName;
	}

	public void setArbitBoardName(String arbitBoardName) {
		this.arbitBoardName = arbitBoardName;
	}

	@Column(name = "PAYTIMES", precision=15, scale=0)
	public Long getPayTimes() {
		return this.payTimes;
	}

	public void setPayTimes(Long payTimes) {
		this.payTimes = payTimes;
	}

	@Column(name = "ENDORSETIMES", precision=15, scale=0)
	public Long getEndorseTimes() {
		return this.endorseTimes;
	}

	public void setEndorseTimes(Long endorseTimes) {
		this.endorseTimes = endorseTimes;
	}

	@Column(name = "CLAIMTIMES", precision=15, scale=0)
	public Long getClaimTimes() {
		return this.claimTimes;
	}

	public void setClaimTimes(Long claimTimes) {
		this.claimTimes = claimTimes;
	}

	@Column(name = "MAKECOM", nullable = false, length=8)
	public String getMakeCom() {
		return this.makeCom;
	}

	public void setMakeCom(String makeCom) {
		this.makeCom = makeCom;
	}

	@Column(name = "OPERATESITE", length=40)
	public String getOperateSite() {
		return this.operateSite;
	}

	public void setOperateSite(String operateSite) {
		this.operateSite = operateSite;
	}

	@Column(name = "COMCODE", nullable = false, length=8)
	public String getComCode() {
		return this.comCode;
	}

	public void setComCode(String comCode) {
		this.comCode = comCode;
	}

	@Column(name = "HANDLERCODE", nullable = false, length=14)
	public String getHandlerCode() {
		return this.handlerCode;
	}

	public void setHandlerCode(String handlerCode) {
		this.handlerCode = handlerCode;
	}

	@Column(name = "HANDLER1CODE", length=10)
	public String getHandler1Code() {
		return this.handler1Code;
	}

	public void setHandler1Code(String handler1Code) {
		this.handler1Code = handler1Code;
	}

	@Column(name = "APPROVERCODE", length=10)
	public String getApproverCode() {
		return this.approverCode;
	}

	public void setApproverCode(String approverCode) {
		this.approverCode = approverCode;
	}

	@Column(name = "UNDERWRITECODE", length=10)
	public String getUnderWriteCode() {
		return this.underWriteCode;
	}

	public void setUnderWriteCode(String underWriteCode) {
		this.underWriteCode = underWriteCode;
	}

	@Column(name = "UNDERWRITENAME", length=40)
	public String getUnderWriteName() {
		return this.underWriteName;
	}

	public void setUnderWriteName(String underWriteName) {
		this.underWriteName = underWriteName;
	}

	@Column(name = "OPERATORCODE", nullable = false, length=10)
	public String getOperatorCode() {
		return this.operatorCode;
	}

	public void setOperatorCode(String operatorCode) {
		this.operatorCode = operatorCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INPUTDATE", length=7)
	public Date getInputDate() {
		return this.inputDate;
	}

	public void setInputDate(Date inputDate) {
		this.inputDate = inputDate;
	}

	@Column(name = "INPUTHOUR", precision=15, scale=0)
	public Long getInputHour() {
		return this.inputHour;
	}

	public void setInputHour(Long inputHour) {
		this.inputHour = inputHour;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UNDERWRITEENDDATE", length=7)
	public Date getUnderWriteEndDate() {
		return this.underWriteEndDate;
	}

	public void setUnderWriteEndDate(Date underWriteEndDate) {
		this.underWriteEndDate = underWriteEndDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "STATISTICSYM", length=7)
	public Date getStatisticsYm() {
		return this.statisticsYm;
	}

	public void setStatisticsYm(Date statisticsYm) {
		this.statisticsYm = statisticsYm;
	}

	@Column(name = "AGENTCODE", length=12)
	public String getAgentCode() {
		return this.agentCode;
	}

	public void setAgentCode(String agentCode) {
		this.agentCode = agentCode;
	}

	@Column(name = "COINSFLAG", length=1)
	public String getCoinsFlag() {
		return this.coinsFlag;
	}

	public void setCoinsFlag(String coinsFlag) {
		this.coinsFlag = coinsFlag;
	}

	@Column(name = "REINSFLAG", length=1)
	public String getReinsFlag() {
		return this.reinsFlag;
	}

	public void setReinsFlag(String reinsFlag) {
		this.reinsFlag = reinsFlag;
	}

	@Column(name = "ALLINSFLAG", length=1)
	public String getAllinsFlag() {
		return this.allinsFlag;
	}

	public void setAllinsFlag(String allinsFlag) {
		this.allinsFlag = allinsFlag;
	}

	@Column(name = "UNDERWRITEFLAG", length=1)
	public String getUnderWriteFlag() {
		return this.underWriteFlag;
	}

	public void setUnderWriteFlag(String underWriteFlag) {
		this.underWriteFlag = underWriteFlag;
	}

	@Column(name = "OTHFLAG", length=20)
	public String getOthFlag() {
		return this.othFlag;
	}

	public void setOthFlag(String othFlag) {
		this.othFlag = othFlag;
	}

	@Column(name = "FLAG", length=10)
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	@Column(name = "DISRATE1", precision=8, scale=4)
	public BigDecimal getDisrate1() {
		return this.disrate1;
	}

	public void setDisrate1(BigDecimal disrate1) {
		this.disrate1 = disrate1;
	}

	@Column(name = "BUSINESSFLAG", length=1)
	public String getBusinessFlag() {
		return this.businessFlag;
	}

	public void setBusinessFlag(String businessFlag) {
		this.businessFlag = businessFlag;
	}

	@Column(name = "UPDATERCODE", length=10)
	public String getUpdaterCode() {
		return this.updaterCode;
	}

	public void setUpdaterCode(String updaterCode) {
		this.updaterCode = updaterCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATEDATE", length=7)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "UPDATEHOUR", length=8)
	public String getUpdateHour() {
		return this.updateHour;
	}

	public void setUpdateHour(String updateHour) {
		this.updateHour = updateHour;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SIGNDATE", length=7)
	public Date getSignDate() {
		return this.signDate;
	}

	public void setSignDate(Date signDate) {
		this.signDate = signDate;
	}

	@Column(name = "SHAREHOLDERFLAG", length=1)
	public String getShareHolderFlag() {
		return this.shareHolderFlag;
	}

	public void setShareHolderFlag(String shareHolderFlag) {
		this.shareHolderFlag = shareHolderFlag;
	}

	@Column(name = "AGREEMENTNO", length=22)
	public String getAgreementNo() {
		return this.agreementNo;
	}

	public void setAgreementNo(String agreementNo) {
		this.agreementNo = agreementNo;
	}

	@Column(name = "INQUIRYNO", length=22)
	public String getInquiryNo() {
		return this.inquiryNo;
	}

	public void setInquiryNo(String inquiryNo) {
		this.inquiryNo = inquiryNo;
	}

	@Column(name = "PAYMODE", length=1)
	public String getPayMode() {
		return this.payMode;
	}

	public void setPayMode(String payMode) {
		this.payMode = payMode;
	}

	@Column(name = "REMARK", length=1000)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "VISACODE", length=20)
	public String getVisaCode() {
		return this.visaCode;
	}

	public void setVisaCode(String visaCode) {
		this.visaCode = visaCode;
	}

	@Column(name = "MANUALTYPE", length=1)
	public String getManualType() {
		return this.manualType;
	}

	public void setManualType(String manualType) {
		this.manualType = manualType;
	}

	@Column(name = "STARTMINUTE", precision=5, scale=0)
	public Integer getStartMinute() {
		return this.startMinute;
	}

	public void setStartMinute(Integer startMinute) {
		this.startMinute = startMinute;
	}

	@Column(name = "ENDMINUTE", precision=5, scale=0)
	public Integer getEndMinute() {
		return this.endMinute;
	}

	public void setEndMinute(Integer endMinute) {
		this.endMinute = endMinute;
	}

	@Column(name = "NATIONFLAG", length=5)
	public String getNationFlag() {
		return this.nationFlag;
	}

	public void setNationFlag(String nationFlag) {
		this.nationFlag = nationFlag;
	}

	@Column(name = "JFEEFLAG", length=1)
	public String getJfeeFlag() {
		return this.jfeeFlag;
	}

	public void setJfeeFlag(String jfeeFlag) {
		this.jfeeFlag = jfeeFlag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PRECHECKDATE", length=7)
	public Date getPrecheckDate() {
		return this.precheckDate;
	}

	public void setPrecheckDate(Date precheckDate) {
		this.precheckDate = precheckDate;
	}

	@Column(name = "HANDLERNAME", length=30)
	public String getHandlerName() {
		return this.handlerName;
	}

	public void setHandlerName(String handlerName) {
		this.handlerName = handlerName;
	}

	@Column(name = "HANDLER1NAME", length=30)
	public String getHandler1Name() {
		return this.handler1Name;
	}

	public void setHandler1Name(String handler1Name) {
		this.handler1Name = handler1Name;
	}

	@Column(name = "PAYREFCODE", length=20)
	public String getPayrefCode() {
		return this.payrefCode;
	}

	public void setPayrefCode(String payrefCode) {
		this.payrefCode = payrefCode;
	}

	@Column(name = "PAYREFNAME", length=30)
	public String getPayrefName() {
		return this.payrefName;
	}

	public void setPayrefName(String payrefName) {
		this.payrefName = payrefName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PAYREFTIME", length=7)
	public Date getPayrefTime() {
		return this.payrefTime;
	}

	public void setPayrefTime(Date payrefTime) {
		this.payrefTime = payrefTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PRINTTIME", length=7)
	public Date getPrintTime() {
		return this.printTime;
	}

	public void setPrintTime(Date printTime) {
		this.printTime = printTime;
	}

	@Column(name = "PRINTTIMES", precision=2, scale=0)
	public Byte getPrintTimes() {
		return this.printTimes;
	}

	public void setPrintTimes(Byte printTimes) {
		this.printTimes = printTimes;
	}

	@Column(name = "COINSCOMCODE", length=8)
	public String getCoinsComCode() {
		return this.coinsComCode;
	}

	public void setCoinsComCode(String coinsComCode) {
		this.coinsComCode = coinsComCode;
	}

	@Column(name = "BUSINESSCLASS", length=2)
	public String getBusinessClass() {
		return this.businessClass;
	}

	public void setBusinessClass(String businessClass) {
		this.businessClass = businessClass;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATETIME", length=7)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INPUTTIME", length=7)
	public Date getInputTime() {
		return this.inputTime;
	}

	public void setInputTime(Date inputTime) {
		this.inputTime = inputTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UNDERWRITEENDTIME", length=7)
	public Date getUnderWriteEndTime() {
		return this.underWriteEndTime;
	}

	public void setUnderWriteEndTime(Date underWriteEndTime) {
		this.underWriteEndTime = underWriteEndTime;
	}

	@Column(name = "FARMFLAG", length=10)
	public String getFarmFlag() {
		return this.farmFlag;
	}

	public void setFarmFlag(String farmFlag) {
		this.farmFlag = farmFlag;
	}

	@Column(name = "OTHERBUSINESSFLAG", length=10)
	public String getOtherBusinessFlag() {
		return this.otherBusinessFlag;
	}

	public void setOtherBusinessFlag(String otherBusinessFlag) {
		this.otherBusinessFlag = otherBusinessFlag;
	}

	@Column(name = "FOREIGNFLAG", length=10)
	public String getForeignFlag() {
		return this.foreignFlag;
	}

	public void setForeignFlag(String foreignFlag) {
		this.foreignFlag = foreignFlag;
	}

	@Column(name = "STOCKHOLDERCODE", length=30)
	public String getStockholderCode() {
		return this.stockholderCode;
	}

	public void setStockholderCode(String stockholderCode) {
		this.stockholderCode = stockholderCode;
	}

	@Column(name = "STOCKHOLDERNAME", length=50)
	public String getStockholderName() {
		return this.stockholderName;
	}

	public void setStockholderName(String stockholderName) {
		this.stockholderName = stockholderName;
	}

	@Column(name = "STOPTIMES", length=10)
	public String getStopTimes() {
		return this.stopTimes;
	}

	public void setStopTimes(String stopTimes) {
		this.stopTimes = stopTimes;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "NEWSTARTDATE", length=7)
	public Date getNewStartDate() {
		return this.newStartDate;
	}

	public void setNewStartDate(Date newStartDate) {
		this.newStartDate = newStartDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "NEWENDDATE", length=7)
	public Date getNewendDate() {
		return this.newendDate;
	}

	public void setNewendDate(Date newendDate) {
		this.newendDate = newendDate;
	}

	@Column(name = "BUSINESSPLATE", length=1)
	public String getBusinessPlate() {
		return businessPlate;
	}

	public void setBusinessPlate(String businessPlate) {
		this.businessPlate = businessPlate;
	}

	@Column(name = "MERCHANTCODE", length=30)
	public String getMerchantcode() {
		return this.merchantcode;
	}

	public void setMerchantcode(String merchantcode) {
		this.merchantcode = merchantcode;
	}

	@Column(name = "MERCHANTNAME", length=250)
	public String getMerchantname() {
		return this.merchantname;
	}

	public void setMerchantname(String merchantname) {
		this.merchantname = merchantname;
	}

	@Column(name = "MERCHANTSUBCODE", length=30)
	public String getMerchantsubcode() {
		return this.merchantsubcode;
	}

	public void setMerchantsubcode(String merchantsubcode) {
		this.merchantsubcode = merchantsubcode;
	}

	@Column(name = "MERCHANTSUBNAME", length=250)
	public String getMerchantsubname() {
		return this.merchantsubname;
	}

	public void setMerchantsubname(String merchantsubname) {
		this.merchantsubname = merchantsubname;
	}

	@Column(name = "VIPFLAG", length=1)
	public String getVipflag() {
		return this.vipflag;
	}

	public void setVipflag(String vipflag) {
		this.vipflag = vipflag;
	}

	@Column(name = "ADDITIONALCOSTRATE", precision=8)
	public BigDecimal getAdditionalcostrate() {
		return this.additionalcostrate;
	}

	public void setAdditionalcostrate(BigDecimal additionalcostrate) {
		this.additionalcostrate = additionalcostrate;
	}

	@Column(name = "SHORTRATE", precision=8, scale=4)
	public BigDecimal getShortRate() {
		return this.shortRate;
	}

	public void setShortRate(BigDecimal shortRate) {
		this.shortRate = shortRate;
	}

	@Column(name = "BUSINESSSUBCLASS", length=50)
	public String getBusinesssubclass() {
		return this.businesssubclass;
	}

	public void setBusinesssubclass(String businesssubclass) {
		this.businesssubclass = businesssubclass;
	}

	@Column(name = "DEFINED1", length=50)
	public String getDefined1() {
		return this.defined1;
	}

	public void setDefined1(String defined1) {
		this.defined1 = defined1;
	}

	@Column(name = "SUMRESERVEPREMIUM", precision=16, scale=8)
	public BigDecimal getSumreservepremium() {
		return this.sumreservepremium;
	}

	public void setSumreservepremium(BigDecimal sumreservepremium) {
		this.sumreservepremium = sumreservepremium;
	}

	@Column(name = "BUSINESSDEMANDNO", length=50)
	public String getBusinessdemandno() {
		return this.businessdemandno;
	}

	public void setBusinessdemandno(String businessdemandno) {
		this.businessdemandno = businessdemandno;
	}

	@Column(name = "RESERVEDEMANDNO", length=50)
	public String getReservedemandno() {
		return this.reservedemandno;
	}

	public void setReservedemandno(String reservedemandno) {
		this.reservedemandno = reservedemandno;
	}

	@Column(name = "AUTOPRICEDEMANDNO", length=50)
	public String getAutopricedemandno() {
		return this.autopricedemandno;
	}

	public void setAutopricedemandno(String autopricedemandno) {
		this.autopricedemandno = autopricedemandno;
	}

	@Column(name = "MANUALFLAG", length=1)
	public String getManualflag() {
		return this.manualflag;
	}

	public void setManualflag(String manualflag) {
		this.manualflag = manualflag;
	}

	@Column(name = "GROUPNO1", length=10)
	public String getGroupno1() {
		return this.groupno1;
	}

	public void setGroupno1(String groupno1) {
		this.groupno1 = groupno1;
	}

	@Column(name = "GROUPNO2", length=10)
	public String getGroupno2() {
		return this.groupno2;
	}

	public void setGroupno2(String groupno2) {
		this.groupno2 = groupno2;
	}

    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCMain")
	public List<PrpCInsured> getPrpCInsureds() {
		return this.prpCInsureds;
	}

	public void setPrpCInsureds(List<PrpCInsured> prpCInsureds) {
		this.prpCInsureds = prpCInsureds;
	}

    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCMain")
	public List<PrpCItemKind> getPrpCItemKinds() {
		return this.prpCItemKinds;
	}

	public void setPrpCItemKinds(List<PrpCItemKind> prpCItemKinds) {
		this.prpCItemKinds = prpCItemKinds;
	}

    @OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCMain")
	public List<PrpCItemCar> getPrpCItemCars() {
		return this.prpCItemCars;
	}

	public void setPrpCItemCars(List<PrpCItemCar> prpCItemCars) {
		this.prpCItemCars = prpCItemCars;
	}

	@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prpCMain")
	public List<PrpCengage> getPrpCengages() {
		return prpCengages;
	}

	public void setPrpCengages(List<PrpCengage> prpCengages) {
		this.prpCengages = prpCengages;
	}
	
	@Column(name = "SERVICEMOBILE", length=15)
	public String getServiceMobile() {
		return serviceMobile;
	}

	public void setServiceMobile(String serviceMobile) {
		this.serviceMobile = serviceMobile;
	}
	
	
}
