package ins.sino.claimcar.regist.po;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!
import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.constraints.NotBlank;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * POJO Class PrpLCengage
 */
@Entity
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "PRPLCENGAGE")
public class PrpLCengage implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Long engageId;
	private PrpLCMain prpLCMain;
	private String policyNo;
	private String riskCode;
	private String registNo;
	private Long lineNo;
	private String clauseCode;
	private String clauseName;
	private String clauses;
	private String titleFlag;
	private String validFlag;
	private String flag;
	private String remark;
	private String createUser;
	private Date createTime;
	private String updateUser;
	private Date updateTime;

	@Id
	@SequenceGenerator(name="sequence",sequenceName="SEQ_PRPLCENGAGE",allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="sequence")
	@Column(name = "ENGAGEID", unique = true, nullable = false, scale=0)
	public Long getEngageId() {
		return this.engageId;
	}

	public void setEngageId(Long engageId) {
		this.engageId = engageId;
	}

	@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PRPLCMAINID")
	public PrpLCMain getPrpLCMain() {
		return this.prpLCMain;
	}

	public void setPrpLCMain(PrpLCMain prpLCMain) {
		this.prpLCMain = prpLCMain;
	}

	@Column(name = "POLICYNO", length=22)
	public String getPolicyNo() {
		return this.policyNo;
	}

	public void setPolicyNo(String policyNo) {
		this.policyNo = policyNo;
	}

	@Column(name = "RISKCODE", length=4)
	public String getRiskCode() {
		return this.riskCode;
	}

	public void setRiskCode(String riskCode) {
		this.riskCode = riskCode;
	}

	@Column(name = "REGISTNO", length=30)
	public String getRegistNo() {
		return this.registNo;
	}

	public void setRegistNo(String registNo) {
		this.registNo = registNo;
	}

	@Column(name = "LINENO", precision=15, scale=0)
	public Long getLineNo() {
		return this.lineNo;
	}

	public void setLineNo(Long lineNo) {
		this.lineNo = lineNo;
	}

	@Column(name = "CLAUSECODE", length=10)
	public String getClauseCode() {
		return this.clauseCode;
	}

	public void setClauseCode(String clauseCode) {
		this.clauseCode = clauseCode;
	}

	@Column(name = "CLAUSENAME", length=120)
	public String getClauseName() {
		return this.clauseName;
	}

	public void setClauseName(String clauseName) {
		this.clauseName = clauseName;
	}

	@Column(name = "CLAUSES", length=1000)
	public String getClauses() {
		return this.clauses;
	}

	public void setClauses(String clauses) {
		this.clauses = clauses;
	}

	@Column(name = "TITLEFLAG", length=1)
	public String getTitleFlag() {
		return this.titleFlag;
	}

	public void setTitleFlag(String titleFlag) {
		this.titleFlag = titleFlag;
	}

	@Column(name = "VALIDFLAG", length=1)
	public String getValidFlag() {
		return this.validFlag;
	}

	public void setValidFlag(String validFlag) {
		this.validFlag = validFlag;
	}

	@Column(name = "FLAG", length=10)
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	@Column(name = "REMARK", length=200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "CREATEUSER", length=10)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATETIME", length=7)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "UPDATEUSER", length=10)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATETIME", length=7)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}
