package ins.platform.saa.vo;

// Generated by Hibernate Tools 3.2.0.b9 (sinosoft version)

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * SaaGrade generated by Tools.Don't edit.
 */
 
public class SaaGradeVo implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private Long id;
	private String gradeCName;
	private String gradeTName;
	private String gradeEName;
	private String commonGrade;
	private String comCode;
	private String creatorCode;
	private Date createTime;
	private String updaterCode;
	private Date updateTime;
	private String validStatus;
	private String systemTypeName;
	private String remark;
	private String attComCode;
	private List<SaaUserGradeVo> saaUserGrades = new ArrayList<SaaUserGradeVo>(0);

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getGradeCName() {
		return gradeCName;
	}

	public void setGradeCName(String gradeCName) {
		this.gradeCName = gradeCName;
	}

	public String getGradeTName() {
		return gradeTName;
	}

	public void setGradeTName(String gradeTName) {
		this.gradeTName = gradeTName;
	}

	public String getGradeEName() {
		return gradeEName;
	}

	public void setGradeEName(String gradeEName) {
		this.gradeEName = gradeEName;
	}

	public String getCommonGrade() {
		return commonGrade;
	}

	public void setCommonGrade(String commonGrade) {
		this.commonGrade = commonGrade;
	}

	public String getComCode() {
		return comCode;
	}

	public void setComCode(String comCode) {
		this.comCode = comCode;
	}

	public String getCreatorCode() {
		return creatorCode;
	}

	public void setCreatorCode(String creatorCode) {
		this.creatorCode = creatorCode;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getUpdaterCode() {
		return updaterCode;
	}

	public void setUpdaterCode(String updaterCode) {
		this.updaterCode = updaterCode;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getValidStatus() {
		return validStatus;
	}

	public void setValidStatus(String validStatus) {
		this.validStatus = validStatus;
	}

	public String getSystemTypeName() {
		return systemTypeName;
	}

	public void setSystemTypeName(String systemTypeName) {
		this.systemTypeName = systemTypeName;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getAttComCode() {
		return attComCode;
	}

	public void setAttComCode(String attComCode) {
		this.attComCode = attComCode;
	}

	public List<SaaUserGradeVo> getSaaUserGrades() {
		return saaUserGrades;
	}

	public void setSaaUserGrades(List<SaaUserGradeVo> saaUserGrades) {
		this.saaUserGrades = saaUserGrades;
	}

}
