package ins.sino.claimcar.ilog.rule.po;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!
import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * POJO Class PrpLRuleBaseInfoId
 */
@Embeddable
public class PrpLRuleBaseInfoId implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private String ruleId;
	private String ruleNode;

	@Column(name = "RULEID", nullable = false, length=50)
	public String getRuleId() {
		return this.ruleId;
	}

	public void setRuleId(String ruleId) {
		this.ruleId = ruleId;
	}

	@Column(name = "RULENODE", nullable = false, length=10)
	public String getRuleNode() {
		return this.ruleNode;
	}

	public void setRuleNode(String ruleNode) {
		this.ruleNode = ruleNode;
	}
	public boolean equals(Object other) {
		if ((this == other)) {
			return true;
		}
		if ((other == null)) {
			return false;
		}
		
		if (!(other instanceof PrpLRuleBaseInfoId)) {
			return false;
		}
		PrpLRuleBaseInfoId castOther = (PrpLRuleBaseInfoId) other;  
		return ( (this.getRuleId()==castOther.getRuleId()) || ( this.getRuleId()!=null && castOther.getRuleId()!=null && this.getRuleId().equals(castOther.getRuleId()) ) )
 && ( (this.getRuleNode()==castOther.getRuleNode()) || ( this.getRuleNode()!=null && castOther.getRuleNode()!=null && this.getRuleNode().equals(castOther.getRuleNode()) ) );
	}
   
	public int hashCode() {
		int result = 17;         
		result = 37 * result + ( getRuleId() == null ? 0 : this.getRuleId().hashCode() );
		result = 37 * result + ( getRuleNode() == null ? 0 : this.getRuleNode().hashCode() );
		return result;
   }   
}
