package ins.sino.claimcar.lossperson.vo;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;


/**
 * Vo Base Class of PO PrpLDlossPersTrace
 */ 
public class PrpLDlossPersTraceVoBase implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Long id;
	private Long persTraceMainId;
	private String registNo;
	private Long injuredId;
	private Long checkPersonId;
	private String personName;
	private String lossFeeType;
	private String traceForms;
	private String endFlag;
	private BigDecimal sumReportFee;
	private BigDecimal sumRealFee;
	private BigDecimal sumDetractionFee;
	private BigDecimal sumdefLoss;
	private BigDecimal sumVeriReportFee;
	private BigDecimal sumVeriRealFee;
	private BigDecimal sumVeriDetractionFee;
	private BigDecimal sumVeriDefloss;
	private String operatorCode;
	private String makeCom;
	private String comCode;
	private String lossState;
	private String validFlag;
	private String flag;
	private String remark;
	private String operatorDesc;
	private String createUser;
	private Date createTime;
	private String updateUser;
	private Date updateTime;
	private Date operatorTime;
	private String undwrtCode;
	private Date undwrtTime;
	private String undwrtDesc;
	private String payTimes;
	private PrpLDlossPersInjuredVo prpLDlossPersInjured;
	private List<PrpLDlossPersTraceFeeVo> prpLDlossPersTraceFees = new ArrayList<PrpLDlossPersTraceFeeVo>(0);

    protected PrpLDlossPersTraceVoBase() {
	
    }

    
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getPersTraceMainId() {
		return this.persTraceMainId;
	}

	public void setPersTraceMainId(Long persTraceMainId) {
		this.persTraceMainId = persTraceMainId;
	}

	public String getRegistNo() {
		return this.registNo;
	}

	public void setRegistNo(String registNo) {
		this.registNo = registNo;
	}

	public Long getInjuredId() {
		return this.injuredId;
	}

	public void setInjuredId(Long injuredId) {
		this.injuredId = injuredId;
	}

	public Long getCheckPersonId() {
		return this.checkPersonId;
	}

	public void setCheckPersonId(Long checkPersonId) {
		this.checkPersonId = checkPersonId;
	}

	public String getPersonName() {
		return this.personName;
	}

	public void setPersonName(String personName) {
		this.personName = personName;
	}

	public String getLossFeeType() {
		return this.lossFeeType;
	}

	public void setLossFeeType(String lossFeeType) {
		this.lossFeeType = lossFeeType;
	}

	public String getTraceForms() {
		return this.traceForms;
	}

	public void setTraceForms(String traceForms) {
		this.traceForms = traceForms;
	}

	public String getEndFlag() {
		return this.endFlag;
	}

	public void setEndFlag(String endFlag) {
		this.endFlag = endFlag;
	}

	public BigDecimal getSumReportFee() {
		return this.sumReportFee;
	}

	public void setSumReportFee(BigDecimal sumReportFee) {
		this.sumReportFee = sumReportFee;
	}

	public BigDecimal getSumRealFee() {
		return this.sumRealFee;
	}

	public void setSumRealFee(BigDecimal sumRealFee) {
		this.sumRealFee = sumRealFee;
	}

	public BigDecimal getSumDetractionFee() {
		return this.sumDetractionFee;
	}

	public void setSumDetractionFee(BigDecimal sumDetractionFee) {
		this.sumDetractionFee = sumDetractionFee;
	}

	public BigDecimal getSumdefLoss() {
		return this.sumdefLoss;
	}

	public void setSumdefLoss(BigDecimal sumdefLoss) {
		this.sumdefLoss = sumdefLoss;
	}

	public BigDecimal getSumVeriReportFee() {
		return this.sumVeriReportFee;
	}

	public void setSumVeriReportFee(BigDecimal sumVeriReportFee) {
		this.sumVeriReportFee = sumVeriReportFee;
	}

	public BigDecimal getSumVeriRealFee() {
		return this.sumVeriRealFee;
	}

	public void setSumVeriRealFee(BigDecimal sumVeriRealFee) {
		this.sumVeriRealFee = sumVeriRealFee;
	}

	public BigDecimal getSumVeriDetractionFee() {
		return this.sumVeriDetractionFee;
	}

	public void setSumVeriDetractionFee(BigDecimal sumVeriDetractionFee) {
		this.sumVeriDetractionFee = sumVeriDetractionFee;
	}

	public BigDecimal getSumVeriDefloss() {
		return this.sumVeriDefloss;
	}

	public void setSumVeriDefloss(BigDecimal sumVeriDefloss) {
		this.sumVeriDefloss = sumVeriDefloss;
	}

	public String getOperatorCode() {
		return this.operatorCode;
	}

	public void setOperatorCode(String operatorCode) {
		this.operatorCode = operatorCode;
	}

	public String getMakeCom() {
		return this.makeCom;
	}

	public void setMakeCom(String makeCom) {
		this.makeCom = makeCom;
	}

	public String getComCode() {
		return this.comCode;
	}

	public void setComCode(String comCode) {
		this.comCode = comCode;
	}

	public String getLossState() {
		return this.lossState;
	}

	public void setLossState(String lossState) {
		this.lossState = lossState;
	}

	public String getValidFlag() {
		return this.validFlag;
	}

	public void setValidFlag(String validFlag) {
		this.validFlag = validFlag;
	}

	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getOperatorDesc() {
		return this.operatorDesc;
	}

	public void setOperatorDesc(String operatorDesc) {
		this.operatorDesc = operatorDesc;
	}

	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	
	public Date getOperatorTime() {
		return operatorTime;
	}


	
	public void setOperatorTime(Date operatorTime) {
		this.operatorTime = operatorTime;
	}


	
	public String getUndwrtCode() {
		return undwrtCode;
	}


	
	public void setUndwrtCode(String undwrtCode) {
		this.undwrtCode = undwrtCode;
	}


	
	public Date getUndwrtTime() {
		return undwrtTime;
	}


	
	public void setUndwrtTime(Date undwrtTime) {
		this.undwrtTime = undwrtTime;
	}


	
	public String getUndwrtDesc() {
		return undwrtDesc;
	}


	
	public void setUndwrtDesc(String undwrtDesc) {
		this.undwrtDesc = undwrtDesc;
	}


	public PrpLDlossPersInjuredVo getPrpLDlossPersInjured() {
		return this.prpLDlossPersInjured;
	}

	public void setPrpLDlossPersInjured(PrpLDlossPersInjuredVo prpLDlossPersInjured) {
		this.prpLDlossPersInjured = prpLDlossPersInjured;
	}

	public List<PrpLDlossPersTraceFeeVo> getPrpLDlossPersTraceFees() {
		return this.prpLDlossPersTraceFees;
	}

	public void setPrpLDlossPersTraceFees(List<PrpLDlossPersTraceFeeVo> prpLDlossPersTraceFees) {
		this.prpLDlossPersTraceFees = prpLDlossPersTraceFees;
	}


	public String getPayTimes() {
		return payTimes;
	}


	public void setPayTimes(String payTimes) {
		this.payTimes = payTimes;
	}
	
}
