package ins.sino.claimcar.claim.po;

// Generated by Hibernate Tools 3.2.5 (sinosoft version), Don't modify!
import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * POJO Class PrpLPrePay
 */
@Entity
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@TableGenerator(name = "utiSequence", table = "UTISEQUENCE", pkColumnName = "GenName", valueColumnName = "GenValue", pkColumnValue = "PRPLPREPAY_PK", allocationSize = 10)
@Table(name = "PRPLPREPAY")
public class PrpLPrePay implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Long id;
	private String compensateNo;
	private String policyNo;
	private String riskCode;
	private String kindCode;
	private String feeType;
	private String chargeCode;
	private String chargeName;
	private String licenseNo;
	private String currency;
	private BigDecimal exchRate;
	private String insuredCode;
	private String insuredName;
	private BigDecimal payAmt;
	private BigDecimal payClaimAmt;
	private String payeeName;
	private String payeeIdfNo;
	private String payObjectKind;
	private String bankName;
	private String accountNo;
	private String otherFlag;
	private String otherCause;
	private Long relateId;
	private String validFlag;
	private String flag;
	private String remark;
	private Date createTime;
	private Date updateTime;
	private String lossType;
	private String lossName;
	private String serialNo;
	private String payStatus;
	private Date payTime;
	private Long payeeId;
	private String summary;
	private String settleNo;
	
	private String invoiceType;
	private String addTaxRate;
	private String addTaxValue;
	private String noTaxValue;
	private String vatInvoiceFlag;
	private String vatTaxRate;
	private BigDecimal regsumAmount;

	/** 平安赔付次数 */
	private Integer caseTimes;
	/** 平安支付信息主键 */
	private String idClmPaymentResult;
	@Id
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "utiSequence")
	@Column(name = "ID", unique = true, nullable = false, precision=13, scale=0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "COMPENSATENO", nullable = false, length=22)
	public String getCompensateNo() {
		return this.compensateNo;
	}

	public void setCompensateNo(String compensateNo) {
		this.compensateNo = compensateNo;
	}

	@Column(name = "POLICYNO", length=22)
	public String getPolicyNo() {
		return this.policyNo;
	}

	public void setPolicyNo(String policyNo) {
		this.policyNo = policyNo;
	}

	@Column(name = "RISKCODE", nullable = false, length=5)
	public String getRiskCode() {
		return this.riskCode;
	}

	public void setRiskCode(String riskCode) {
		this.riskCode = riskCode;
	}

	@Column(name = "KINDCODE", length=6)
	public String getKindCode() {
		return this.kindCode;
	}

	public void setKindCode(String kindCode) {
		this.kindCode = kindCode;
	}

	@Column(name = "FEETYPE", nullable = false, length=4)
	public String getFeeType() {
		return this.feeType;
	}

	public void setFeeType(String feeType) {
		this.feeType = feeType;
	}

	@Column(name = "CHARGECODE", nullable = false, length=3)
	public String getChargeCode() {
		return this.chargeCode;
	}

	public void setChargeCode(String chargeCode) {
		this.chargeCode = chargeCode;
	}

	@Column(name = "CHARGENAME", length=16)
	public String getChargeName() {
		return this.chargeName;
	}

	public void setChargeName(String chargeName) {
		this.chargeName = chargeName;
	}

	@Column(name = "LICENSENO", length=20)
	public String getLicenseNo() {
		return licenseNo;
	}

	
	public void setLicenseNo(String licenseNo) {
		this.licenseNo = licenseNo;
	}

	@Column(name = "CURRENCY", nullable = false, length=3)
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	@Column(name = "EXCHRATE", precision=8)
	public BigDecimal getExchRate() {
		return this.exchRate;
	}

	public void setExchRate(BigDecimal exchRate) {
		this.exchRate = exchRate;
	}

	@Column(name = "INSUREDCODE", nullable = false, length=20)
	public String getInsuredCode() {
		return this.insuredCode;
	}

	public void setInsuredCode(String insuredCode) {
		this.insuredCode = insuredCode;
	}

	@Column(name = "INSUREDNAME", nullable = false, length=200)
	public String getInsuredName() {
		return this.insuredName;
	}

	public void setInsuredName(String insuredName) {
		this.insuredName = insuredName;
	}

	@Column(name = "PAYAMT", nullable = false, precision=14)
	public BigDecimal getPayAmt() {
		return this.payAmt;
	}

	public void setPayAmt(BigDecimal payAmt) {
		this.payAmt = payAmt;
	}

	@Column(name = "PAYCLAIMAMT", nullable = false, precision=14)
	public BigDecimal getPayClaimAmt() {
		return this.payClaimAmt;
	}

	public void setPayClaimAmt(BigDecimal payClaimAmt) {
		this.payClaimAmt = payClaimAmt;
	}

	@Column(name = "PAYEENAME", nullable = false, length=20)
	public String getPayeeName() {
		return this.payeeName;
	}

	public void setPayeeName(String payeeName) {
		this.payeeName = payeeName;
	}

	@Column(name = "PAYEEIDFNO", nullable = false, length=20)
	public String getPayeeIdfNo() {
		return payeeIdfNo;
	}

	
	public void setPayeeIdfNo(String payeeIdfNo) {
		this.payeeIdfNo = payeeIdfNo;
	}

	@Column(name = "PAYOBJECTKIND", nullable = false, length=20)
	public String getPayObjectKind() {
		return payObjectKind;
	}

	
	public void setPayObjectKind(String payObjectKind) {
		this.payObjectKind = payObjectKind;
	}

	@Column(name = "BANKNAME", nullable = false, length=200)
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@Column(name = "ACCOUNTNO", nullable = false, length=20)
	public String getAccountNo() {
		return this.accountNo;
	}

	public void setAccountNo(String accountNo) {
		this.accountNo = accountNo;
	}

	@Column(name = "OTHERFLAG", nullable = false, length=2)
	public String getOtherFlag() {
		return this.otherFlag;
	}

	public void setOtherFlag(String otherFlag) {
		this.otherFlag = otherFlag;
	}

	@Column(name = "OTHERCAUSE", length=5)
	public String getOtherCause() {
		return this.otherCause;
	}

	public void setOtherCause(String otherCause) {
		this.otherCause = otherCause;
	}

	@Column(name = "RELATEID", precision=10, scale=0)
	public Long getRelateId() {
		return this.relateId;
	}

	public void setRelateId(Long relateId) {
		this.relateId = relateId;
	}

	@Column(name = "VALIDFLAG", nullable = false, length=1)
	public String getValidFlag() {
		return this.validFlag;
	}

	public void setValidFlag(String validFlag) {
		this.validFlag = validFlag;
	}

	@Column(name = "FLAG", length=10)
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	@Column(name = "LOSSTYPE", length=20)
	public String getLossType() {
		return lossType;
	}
	
	public void setLossType(String lossType) {
		this.lossType = lossType;
	}

	@Column(name = "LOSSNAME", length=200)
	public String getLossName() {
		return lossName;
	}
	
	public void setLossName(String lossName) {
		this.lossName = lossName;
	}

	@Column(name = "REMARK")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATETIME", length=7)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATETIME", length=7)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "SERIALNO", length=4)
	public String getSerialNo() {
		return serialNo;
	}
	
	public void setSerialNo(String serialNo) {
		this.serialNo = serialNo;
	}

	@Column(name = "PAYSTATUS", length=4)
	public String getPayStatus() {
		return payStatus;
	}
	
	public void setPayStatus(String payStatus) {
		this.payStatus = payStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PAYTIME", length=7)
	public Date getPayTime() {
		return payTime;
	}
	
	public void setPayTime(Date payTime) {
		this.payTime = payTime;
	}

	@Column(name = "PAYEEID", nullable = false, scale=0)
	public Long getPayeeId() {
		return payeeId;
	}
	
	public void setPayeeId(Long payeeId) {
		this.payeeId = payeeId;
	}
	
	@Column(name = "SETTLENO", length=50)
	public String getSettleNo() {
		return settleNo;
	}

	public void setSettleNo(String settleNo) {
		this.settleNo = settleNo;
	}
	
    @Column(name = "SUMMARY", length=2000)
    public String getSummary() {
        return summary;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }

    @Column(name = "INVOICETYPE", length=10)
	public String getInvoiceType() {
		return invoiceType;
	}

	public void setInvoiceType(String invoiceType) {
		this.invoiceType = invoiceType;
	}
	
	@Column(name = "ADDTAXRATE", length=10)
	public String getAddTaxRate() {
		return addTaxRate;
	}

	public void setAddTaxRate(String addTaxRate) {
		this.addTaxRate = addTaxRate;
	}

	@Column(name = "ADDTAXVALUE", length=10)
	public String getAddTaxValue() {
		return addTaxValue;
	}

	public void setAddTaxValue(String addTaxValue) {
		this.addTaxValue = addTaxValue;
	}

	@Column(name = "NOTAXVALUE", length=10)
	public String getNoTaxValue() {
		return noTaxValue;
	}

	public void setNoTaxValue(String noTaxValue) {
		this.noTaxValue = noTaxValue;
	}
	
	@Column(name = "VATINVOICEFLAG")
	public String getVatInvoiceFlag() {
		return vatInvoiceFlag;
	}

	public void setVatInvoiceFlag(String vatInvoiceFlag) {
		this.vatInvoiceFlag = vatInvoiceFlag;
	}
	@Column(name = "VATTAXRATE")
	public String getVatTaxRate() {
		return vatTaxRate;
	}

	public void setVatTaxRate(String vatTaxRate) {
		this.vatTaxRate = vatTaxRate;
	}

	public BigDecimal getRegsumAmount() {
		return regsumAmount;
	}

	public void setRegsumAmount(BigDecimal regsumAmount) {
		this.regsumAmount = regsumAmount;
	}
	

	@Column(name = "CASETIMES", length=3)
	public Integer getCaseTimes() {
		return caseTimes;
	}

	public void setCaseTimes(Integer caseTimes) {
		this.caseTimes = caseTimes;
	}
	@Column(name = "IDCLMPAYMENTRESULT", length=50)
	public String getIdClmPaymentResult() {
		return idClmPaymentResult;
	}

	public void setIdClmPaymentResult(String idClmPaymentResult) {
		this.idClmPaymentResult = idClmPaymentResult;
	}
}
